/**
 * Label-sourced contraindication pins for named CYP pairs.
 *
 * Why this exists: the enzyme rule (`pkSeverity` in engine.ts) grades pairs
 * from perpetrator strength and substrate sensitivity. For a short list of
 * pairs, the FDA-approved label itself lists the combination under
 * Contraindications. Those pairs should read "Avoid together" because the
 * label says so, not only because the enzyme grades happen to line up. When a
 * perpetrator grade is corrected to FDA's table (for example ciprofloxacin as a
 * moderate CYP1A2 inhibitor), the enzyme rule alone can drop a
 * label-contraindicated pair. A pin keeps it at contraindicated.
 *
 * Scope rules:
 * - Only exact, named catalog pairs. No class expansion, no global threshold
 *   change. Each pin names one enzyme and one direction (inhibitor or inducer).
 * - `quote`, `labelExample`, `labelSection` and `url` are copied byte-for-byte
 *   from `src/lib/drugs/reference/label-gold-set.ts` (PR #65), so the desk and
 *   the gold-set test cite identical text. Quotes are verbatim DailyMed SPL
 *   text ("…" marks an elided span), retrieved 2026-09-27.
 * - Rows with origin "wave3" copy the same fields byte-for-byte from PR #75
 *   (`feat/label-gold-wave3`, commit f41256d). Those quotes were retrieved
 *   2026-10-02. They pin pairs that already produce a CYP3A4 finding below
 *   contraindicated.
 * - Rows with origin "wave4" copy the same fields byte-for-byte from PR #86
 *   (`feat/label-gold-wave4`, commit 5912f77). Those quotes were retrieved
 *   2026-10-02. They hold an existing enzyme finding (below contraindicated
 *   on main) at contraindicated. One enzyme and one direction, the finding
 *   the pair already produces.
 * - Rows with origin "no-enzyme" copy the same fields from the wave-3 or
 *   wave-4 gold set and omit `enzyme` and `kind`. The desk emits a standalone
 *   contraindicated finding and does not invent a CYP grade. Wave 3 is the
 *   seven pairs whose partner has no CYP role the engine uses (elbasvir/
 *   grazoprevir, irinotecan, drospirenone; irinotecan is UGT1A1, not a CYP).
 *   Wave 4 adds pairs that show no enzyme finding: itraconazole with
 *   dofetilide and irinotecan, Kaletra with elbasvir/grazoprevir, and
 *   Paxlovid with flecainide, phenytoin, rifapentine, and the inducers whose
 *   only row today is a washout clock.
 * - Rows with origin "restored-after-58" are not in the gold set. Their quotes
 *   reuse gold-set strings where the same label sentence applies, or are the
 *   verbatim DailyMed Contraindications text (Ranexa section 4).
 * - `contraindicationsSentence` is added only where the gold-set quote comes
 *   from a section other than Contraindications (Zanaflex 7.1, Ranexa 7.1). It
 *   is the verbatim section 4 sentence from the same DailyMed label.
 *
 * Educational reference, not FDA-cleared. No doses.
 */
import type { Enzyme } from "./types";

export interface LabelContraindication {
  /** Stable id, `labelDrugId+otherId` (matches the gold-set id). */
  id: string;
  /** Catalog id of the drug whose label carries the contraindication. */
  labelDrugId: string;
  /** Catalog id of the other drug (the CYP perpetrator). */
  otherId: string;
  /**
   * Enzyme the pinned finding is on. Omitted when there is no enzyme finding
   * to hold: the pin then emits a standalone contraindicated finding and does
   * not assign a CYP grade.
   */
  enzyme?: Enzyme;
  /** Direction of the perpetrator on that enzyme. Omitted together with `enzyme`. */
  kind?: "inhibitor" | "inducer";
  labelDrug: string;
  labelSection: string;
  quote: string;
  labelExample?: string;
  contraindicationsSentence?: string;
  url: string;
  /**
   * `named`: the label names this drug (in the Contraindications sentence or
   * the example list it points to). `class`: the Contraindications sentence
   * covers a class this drug belongs to (for example "inducers of CYP3A") but
   * does not name it.
   */
  basis: "named" | "class";
  /** Why the pin was added: gold-set pair from PR #65, restored after PR #58 grade changes, a #75 wave-3 pair that still read below contraindicated, a #86 wave-4 pair whose existing enzyme finding is held at contraindicated, or a pair with no enzyme finding to hold. */
  origin: "gold-set" | "restored-after-58" | "wave3" | "wave4" | "no-enzyme";
  /**
   * DailyMed retrieval date for this quote when it is not
   * `LABEL_CONTRAINDICATIONS_RETRIEVED` (wave 3 is 2026-10-02).
   */
  retrieved?: "2026-10-02";
}

export const LABEL_CONTRAINDICATIONS_RETRIEVED = "2026-09-27";

export const LABEL_CONTRAINDICATIONS: readonly LabelContraindication[] = [
  {
    id: "simvastatin+clarithromycin",
    labelDrugId: "simvastatin",
    otherId: "clarithromycin",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Zocor (simvastatin)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Concomitant use of strong CYP3A4 inhibitors (select azole anti-fungals, macrolide antibiotics, anti-viral medications, and nefazodone)",
    labelExample: "select macrolide antibiotics (e.g., erythromycin and clarithromycin)",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f55d5de-5a4f-4a39-8c84-c53976dd6af9",
  },
  {
    id: "simvastatin+itraconazole",
    labelDrugId: "simvastatin",
    otherId: "itraconazole",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Zocor (simvastatin)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Concomitant use of strong CYP3A4 inhibitors (select azole anti-fungals, macrolide antibiotics, anti-viral medications, and nefazodone)",
    labelExample: "Select azole anti-fungals (e.g., itraconazole, ketoconazole, posaconazole, and voriconazole)",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f55d5de-5a4f-4a39-8c84-c53976dd6af9",
  },
  {
    id: "simvastatin+ritonavir",
    labelDrugId: "simvastatin",
    otherId: "ritonavir",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Zocor (simvastatin)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Concomitant use of strong CYP3A4 inhibitors (select azole anti-fungals, macrolide antibiotics, anti-viral medications, and nefazodone)",
    labelExample: "select HIV protease inhibitors (e.g., nelfinavir, ritonavir, and darunavir/ritonavir)",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8f55d5de-5a4f-4a39-8c84-c53976dd6af9",
  },
  {
    id: "lovastatin+clarithromycin",
    labelDrugId: "lovastatin",
    otherId: "clarithromycin",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Lovastatin tablets",
    labelSection: "CONTRAINDICATIONS",
    quote: "Concomitant administration with strong CYP3A4 inhibitors (e.g., itraconazole, ketoconazole, … erythromycin, clarithromycin, telithromycin",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9438d8a0-ca5b-4676-aab9-d0241ccff6c9",
  },
  {
    id: "tizanidine+fluvoxamine",
    labelDrugId: "tizanidine",
    otherId: "fluvoxamine",
    enzyme: "CYP1A2",
    kind: "inhibitor",
    labelDrug: "Zanaflex (tizanidine)",
    labelSection: "7.1 Strong CYP1A2 Inhibitors (see 4 CONTRAINDICATIONS)",
    quote: "Concomitant use of Zanaflex with strong cytochrome P450 1A2 (CYP1A2) inhibitors (e.g., fluvoxamine, ciprofloxacin) is contraindicated.",
    contraindicationsSentence: "Zanaflex is contraindicated in patients taking strong CYP1A2 inhibitors",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=60c27d35-7349-4fc6-86ad-70fffdbe3e08",
  },
  {
    id: "tizanidine+ciprofloxacin",
    labelDrugId: "tizanidine",
    otherId: "ciprofloxacin",
    enzyme: "CYP1A2",
    kind: "inhibitor",
    labelDrug: "Zanaflex (tizanidine)",
    labelSection: "7.1 Strong CYP1A2 Inhibitors (see 4 CONTRAINDICATIONS)",
    quote: "Concomitant use of Zanaflex with strong cytochrome P450 1A2 (CYP1A2) inhibitors (e.g., fluvoxamine, ciprofloxacin) is contraindicated.",
    contraindicationsSentence: "Zanaflex is contraindicated in patients taking strong CYP1A2 inhibitors",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=60c27d35-7349-4fc6-86ad-70fffdbe3e08",
  },
  {
    id: "pimozide+clarithromycin",
    labelDrugId: "pimozide",
    otherId: "clarithromycin",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Pimozide tablets",
    labelSection: "CONTRAINDICATIONS",
    quote: "pimozide is contraindicated in patients receiving the macrolide antibiotics clarithromycin, erythromycin, azithromycin, dirithromycin, and troleandomycin.",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=70b079e2-a1f7-4a93-8685-d60a4d7c1280",
  },
  {
    id: "pimozide+ketoconazole",
    labelDrugId: "pimozide",
    otherId: "ketoconazole",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Pimozide tablets",
    labelSection: "CONTRAINDICATIONS",
    quote: "pimozide is contraindicated in patients receiving the azole antifungal agents itraconazole and ketoconazole.",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=70b079e2-a1f7-4a93-8685-d60a4d7c1280",
  },
  {
    id: "thioridazine+fluoxetine",
    labelDrugId: "thioridazine",
    otherId: "fluoxetine",
    enzyme: "CYP2D6",
    kind: "inhibitor",
    labelDrug: "Thioridazine HCl tablets",
    labelSection: "CONTRAINDICATIONS",
    quote: "drugs that inhibit this isozyme (e.g., fluoxetine and paroxetine) … thioridazine is contraindicated with these drugs",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1fd16a99-e856-4a37-9dae-c443714fac14",
  },
  {
    id: "thioridazine+paroxetine",
    labelDrugId: "thioridazine",
    otherId: "paroxetine",
    enzyme: "CYP2D6",
    kind: "inhibitor",
    labelDrug: "Thioridazine HCl tablets",
    labelSection: "CONTRAINDICATIONS",
    quote: "drugs that inhibit this isozyme (e.g., fluoxetine and paroxetine) … thioridazine is contraindicated with these drugs",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1fd16a99-e856-4a37-9dae-c443714fac14",
  },
  {
    id: "lurasidone+ketoconazole",
    labelDrugId: "lurasidone",
    otherId: "ketoconazole",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Latuda (lurasidone)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Strong CYP3A4 inhibitors (e.g., ketoconazole, clarithromycin, ritonavir, voriconazole, mibefradil, etc.)",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=afad3051-9df2-4c54-9684-e8262a133af8",
  },
  {
    id: "lurasidone+rifampin",
    labelDrugId: "lurasidone",
    otherId: "rifampin",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Latuda (lurasidone)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Strong CYP3A4 inducers (e.g., rifampin, avasimibe, St. John's wort, phenytoin, carbamazepine, etc.)",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=afad3051-9df2-4c54-9684-e8262a133af8",
  },
  {
    id: "ramelteon+fluvoxamine",
    labelDrugId: "ramelteon",
    otherId: "fluvoxamine",
    enzyme: "CYP1A2",
    kind: "inhibitor",
    labelDrug: "Rozerem (ramelteon)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Patients should not take ROZEREM in conjunction with fluvoxamine",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9de82310-70e8-47b9-b1fc-6c6848b99455",
  },
  {
    id: "triazolam+ketoconazole",
    labelDrugId: "triazolam",
    otherId: "ketoconazole",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Triazolam tablets",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Concomitant administration of strong cytochrome P450 (CYP 3A) enzyme inhibitors (e.g., ketoconazole, itraconazole, nefazodone, lopinavir, ritonavir)",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5add318e-11b9-42f8-b052-0d8cebb32fcf",
  },
  {
    id: "ivabradine+clarithromycin",
    labelDrugId: "ivabradine",
    otherId: "clarithromycin",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Corlanor (ivabradine)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Concomitant use of strong cytochrome P450 3A4 (CYP3A4) inhibitors",
    labelExample: "macrolide antibiotics (e.g., clarithromycin, telithromycin)",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=92018a65-38f6-45f7-91d4-a34921b81d0d",
  },
  {
    id: "ranolazine+ketoconazole",
    labelDrugId: "ranolazine",
    otherId: "ketoconazole",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Ranexa (ranolazine)",
    labelSection: "7.1 (see 4 CONTRAINDICATIONS)",
    quote: "Do not use RANEXA with strong CYP3A inhibitors, including ketoconazole, itraconazole, clarithromycin, nefazodone, nelfinavir, ritonavir, indinavir, and saquinavir",
    contraindicationsSentence: "RANEXA is contraindicated in patients: Taking strong inhibitors of CYP3A",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e038f963-d78f-460e-a11f-46f224061505",
  },
  {
    id: "ranolazine+rifampin",
    labelDrugId: "ranolazine",
    otherId: "rifampin",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Ranexa (ranolazine)",
    labelSection: "7.1 (see 4 CONTRAINDICATIONS)",
    quote: "Do not use RANEXA with CYP3A inducers such as rifampin, rifabutin, rifapentine, phenobarbital, phenytoin, carbamazepine",
    contraindicationsSentence: "RANEXA is contraindicated in patients: … Taking inducers of CYP3A",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e038f963-d78f-460e-a11f-46f224061505",
  },
  {
    id: "eplerenone+ketoconazole",
    labelDrugId: "eplerenone",
    otherId: "ketoconazole",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Inspra (eplerenone)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "concomitant administration of strong CYP3A inhibitors (e.g., ketoconazole, itraconazole, nefazodone, troleandomycin, clarithromycin, ritonavir, and nelfinavir)",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1a52bedc-8e2c-4116-a296-a87770676b4a",
  },
  {
    id: "alosetron+fluvoxamine",
    labelDrugId: "alosetron",
    otherId: "fluvoxamine",
    enzyme: "CYP1A2",
    kind: "inhibitor",
    labelDrug: "Lotronex (alosetron)",
    labelSection: "4.3 Concomitant Use of Fluvoxamine",
    quote: "Concomitant administration of LOTRONEX with fluvoxamine is contraindicated.",
    basis: "named",
    origin: "gold-set",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=35cbb9d5-639b-207a-e054-00144ff88e88",
  },
  // ── Restored after #58: were contraindicated on main via the enzyme rule, the
  // label contraindicates them, and #58's FDA-aligned grades dropped them to major.
  {
    id: "ranolazine+phenobarbital",
    labelDrugId: "ranolazine",
    otherId: "phenobarbital",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Ranexa (ranolazine)",
    labelSection: "7.1 (see 4 CONTRAINDICATIONS)",
    quote: "Do not use RANEXA with CYP3A inducers such as rifampin, rifabutin, rifapentine, phenobarbital, phenytoin, carbamazepine",
    contraindicationsSentence: "RANEXA is contraindicated in patients: … Taking inducers of CYP3A",
    basis: "named",
    origin: "restored-after-58",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e038f963-d78f-460e-a11f-46f224061505",
  },
  {
    id: "ranolazine+primidone",
    labelDrugId: "ranolazine",
    otherId: "primidone",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Ranexa (ranolazine)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "RANEXA is contraindicated in patients: … Taking inducers of CYP3A",
    basis: "class",
    origin: "restored-after-58",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e038f963-d78f-460e-a11f-46f224061505",
  },
  {
    id: "thioridazine+abiraterone",
    labelDrugId: "thioridazine",
    otherId: "abiraterone",
    enzyme: "CYP2D6",
    kind: "inhibitor",
    labelDrug: "Thioridazine HCl tablets",
    labelSection: "CONTRAINDICATIONS",
    quote: "drugs that inhibit this isozyme (e.g., fluoxetine and paroxetine) … thioridazine is contraindicated with these drugs",
    basis: "class",
    origin: "restored-after-58",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1fd16a99-e856-4a37-9dae-c443714fac14",
  },
  {
    id: "thioridazine+cinacalcet",
    labelDrugId: "thioridazine",
    otherId: "cinacalcet",
    enzyme: "CYP2D6",
    kind: "inhibitor",
    labelDrug: "Thioridazine HCl tablets",
    labelSection: "CONTRAINDICATIONS",
    quote: "drugs that inhibit this isozyme (e.g., fluoxetine and paroxetine) … thioridazine is contraindicated with these drugs",
    basis: "class",
    origin: "restored-after-58",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1fd16a99-e856-4a37-9dae-c443714fac14",
  },
  // ── Wave 3 (#75): label says contraindicated, the enzyme finding is already
  // present but below contraindicated. Quotes are copied from that gold set.
  // `kind` selects the finding: inducer when the partner lowers the labeled
  // product, inhibitor when the labeled product raises the partner. Sildenafil
  // pins use the PAH row (sildenafil-pah / Revatio), not sildenafil (Viagra).
  {
    id: "mifepristone+dihydroergotamine",
    labelDrugId: "mifepristone",
    otherId: "dihydroergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Korlym (mifepristone)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "KORLYM is contraindicated in: … Patients taking drugs metabolized by CYP3A such as simvastatin, lovastatin",
    labelExample: "such as cyclosporine, dihydroergotamine, ergotamine, fentanyl, pimozide, quinidine, sirolimus, and tacrolimus",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=542f3fae-8bc8-4f00-9228-e4b66c9ad6a9",
  },
  {
    id: "mifepristone+ergotamine",
    labelDrugId: "mifepristone",
    otherId: "ergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Korlym (mifepristone)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "KORLYM is contraindicated in: … Patients taking drugs metabolized by CYP3A such as simvastatin, lovastatin",
    labelExample: "such as cyclosporine, dihydroergotamine, ergotamine, fentanyl, pimozide, quinidine, sirolimus, and tacrolimus",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=542f3fae-8bc8-4f00-9228-e4b66c9ad6a9",
  },
  {
    id: "mifepristone+quinidine",
    labelDrugId: "mifepristone",
    otherId: "quinidine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Korlym (mifepristone)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "KORLYM is contraindicated in: … Patients taking drugs metabolized by CYP3A such as simvastatin, lovastatin",
    labelExample: "such as cyclosporine, dihydroergotamine, ergotamine, fentanyl, pimozide, quinidine, sirolimus, and tacrolimus",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=542f3fae-8bc8-4f00-9228-e4b66c9ad6a9",
  },
  {
    id: "darunavir+rifampin",
    labelDrugId: "darunavir",
    otherId: "rifampin",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Prezista (darunavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of these drugs and other contraindicated drugs (which may lead to reduced efficacy of darunavir) are listed below",
    labelExample: "Antimycobacterial: rifampin",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=814301f9-c990-46a5-b481-2879a521a16f",
  },
  {
    id: "darunavir+dronedarone",
    labelDrugId: "darunavir",
    otherId: "dronedarone",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Prezista (darunavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of these drugs and other contraindicated drugs (which may lead to reduced efficacy of darunavir) are listed below",
    labelExample: "Cardiac Disorders: dronedarone, ivabradine, ranolazine",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=814301f9-c990-46a5-b481-2879a521a16f",
  },
  {
    id: "darunavir+dihydroergotamine",
    labelDrugId: "darunavir",
    otherId: "dihydroergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Prezista (darunavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of these drugs and other contraindicated drugs (which may lead to reduced efficacy of darunavir) are listed below",
    labelExample: "Ergot derivatives, e.g. dihydroergotamine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=814301f9-c990-46a5-b481-2879a521a16f",
  },
  {
    id: "darunavir+ergotamine",
    labelDrugId: "darunavir",
    otherId: "ergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Prezista (darunavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of these drugs and other contraindicated drugs (which may lead to reduced efficacy of darunavir) are listed below",
    labelExample: "Ergot derivatives, e.g. dihydroergotamine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=814301f9-c990-46a5-b481-2879a521a16f",
  },
  {
    id: "darunavir+methylergonovine",
    labelDrugId: "darunavir",
    otherId: "methylergonovine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Prezista (darunavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of these drugs and other contraindicated drugs (which may lead to reduced efficacy of darunavir) are listed below",
    labelExample: "Ergot derivatives, e.g. dihydroergotamine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=814301f9-c990-46a5-b481-2879a521a16f",
  },
  {
    id: "darunavir+st-johns-wort",
    labelDrugId: "darunavir",
    otherId: "st-johns-wort",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Prezista (darunavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of these drugs and other contraindicated drugs (which may lead to reduced efficacy of darunavir) are listed below",
    labelExample: "St. John's wort",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=814301f9-c990-46a5-b481-2879a521a16f",
  },
  {
    id: "darunavir+sildenafil-pah",
    labelDrugId: "darunavir",
    otherId: "sildenafil-pah",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Prezista (darunavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of these drugs and other contraindicated drugs (which may lead to reduced efficacy of darunavir) are listed below",
    labelExample: "sildenafil when used for treatment of pulmonary arterial hypertension",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=814301f9-c990-46a5-b481-2879a521a16f",
  },
  {
    id: "darunavir-cobicistat+carbamazepine",
    labelDrugId: "darunavir-cobicistat",
    otherId: "carbamazepine",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Prezcobix (darunavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of drugs that are contraindicated for co-administration with PREZCOBIX",
    labelExample: "Anticonvulsants: carbamazepine, phenobarbital, phenytoin",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9c38fdb6-d0ba-4f16-a0e3-85d9ec334d9f",
  },
  {
    id: "darunavir-cobicistat+phenobarbital",
    labelDrugId: "darunavir-cobicistat",
    otherId: "phenobarbital",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Prezcobix (darunavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of drugs that are contraindicated for co-administration with PREZCOBIX",
    labelExample: "Anticonvulsants: carbamazepine, phenobarbital, phenytoin",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9c38fdb6-d0ba-4f16-a0e3-85d9ec334d9f",
  },
  {
    id: "darunavir-cobicistat+phenytoin",
    labelDrugId: "darunavir-cobicistat",
    otherId: "phenytoin",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Prezcobix (darunavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of drugs that are contraindicated for co-administration with PREZCOBIX",
    labelExample: "Anticonvulsants: carbamazepine, phenobarbital, phenytoin",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9c38fdb6-d0ba-4f16-a0e3-85d9ec334d9f",
  },
  {
    id: "darunavir-cobicistat+rifampin",
    labelDrugId: "darunavir-cobicistat",
    otherId: "rifampin",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Prezcobix (darunavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of drugs that are contraindicated for co-administration with PREZCOBIX",
    labelExample: "Antimycobacterial: rifampin",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9c38fdb6-d0ba-4f16-a0e3-85d9ec334d9f",
  },
  {
    id: "darunavir-cobicistat+dronedarone",
    labelDrugId: "darunavir-cobicistat",
    otherId: "dronedarone",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Prezcobix (darunavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of drugs that are contraindicated for co-administration with PREZCOBIX",
    labelExample: "Cardiac Disorders: dronedarone, ivabradine, ranolazine",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9c38fdb6-d0ba-4f16-a0e3-85d9ec334d9f",
  },
  {
    id: "darunavir-cobicistat+dihydroergotamine",
    labelDrugId: "darunavir-cobicistat",
    otherId: "dihydroergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Prezcobix (darunavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of drugs that are contraindicated for co-administration with PREZCOBIX",
    labelExample: "Ergot derivatives, e.g. dihydroergotamine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9c38fdb6-d0ba-4f16-a0e3-85d9ec334d9f",
  },
  {
    id: "darunavir-cobicistat+ergotamine",
    labelDrugId: "darunavir-cobicistat",
    otherId: "ergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Prezcobix (darunavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of drugs that are contraindicated for co-administration with PREZCOBIX",
    labelExample: "Ergot derivatives, e.g. dihydroergotamine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9c38fdb6-d0ba-4f16-a0e3-85d9ec334d9f",
  },
  {
    id: "darunavir-cobicistat+methylergonovine",
    labelDrugId: "darunavir-cobicistat",
    otherId: "methylergonovine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Prezcobix (darunavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of drugs that are contraindicated for co-administration with PREZCOBIX",
    labelExample: "Ergot derivatives, e.g. dihydroergotamine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9c38fdb6-d0ba-4f16-a0e3-85d9ec334d9f",
  },
  {
    id: "darunavir-cobicistat+st-johns-wort",
    labelDrugId: "darunavir-cobicistat",
    otherId: "st-johns-wort",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Prezcobix (darunavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of drugs that are contraindicated for co-administration with PREZCOBIX",
    labelExample: "St. John's wort",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9c38fdb6-d0ba-4f16-a0e3-85d9ec334d9f",
  },
  {
    id: "darunavir-cobicistat+sildenafil-pah",
    labelDrugId: "darunavir-cobicistat",
    otherId: "sildenafil-pah",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Prezcobix (darunavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of drugs that are contraindicated for co-administration with PREZCOBIX",
    labelExample: "sildenafil when used for treatment of pulmonary arterial hypertension",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9c38fdb6-d0ba-4f16-a0e3-85d9ec334d9f",
  },
  {
    id: "atazanavir+carbamazepine",
    labelDrugId: "atazanavir",
    otherId: "carbamazepine",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Reyataz (atazanavir)",
    labelSection: "4 CONTRAINDICATIONS (Table 6)",
    quote: "Coadministration is contraindicated with, but not limited to, the following drugs",
    labelExample: "Anticonvulsants Carbamazepine, phenobarbital, phenytoin",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8",
  },
  {
    id: "atazanavir+phenobarbital",
    labelDrugId: "atazanavir",
    otherId: "phenobarbital",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Reyataz (atazanavir)",
    labelSection: "4 CONTRAINDICATIONS (Table 6)",
    quote: "Coadministration is contraindicated with, but not limited to, the following drugs",
    labelExample: "Anticonvulsants Carbamazepine, phenobarbital, phenytoin",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8",
  },
  {
    id: "atazanavir+phenytoin",
    labelDrugId: "atazanavir",
    otherId: "phenytoin",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Reyataz (atazanavir)",
    labelSection: "4 CONTRAINDICATIONS (Table 6)",
    quote: "Coadministration is contraindicated with, but not limited to, the following drugs",
    labelExample: "Anticonvulsants Carbamazepine, phenobarbital, phenytoin",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8",
  },
  {
    id: "atazanavir+apalutamide",
    labelDrugId: "atazanavir",
    otherId: "apalutamide",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Reyataz (atazanavir)",
    labelSection: "4 CONTRAINDICATIONS (Table 6)",
    quote: "Coadministration is contraindicated with, but not limited to, the following drugs",
    labelExample: "Antineoplastics Apalutamide, encorafenib, irinotecan, ivosidenib",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8",
  },
  {
    id: "atazanavir+encorafenib",
    labelDrugId: "atazanavir",
    otherId: "encorafenib",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Reyataz (atazanavir)",
    labelSection: "4 CONTRAINDICATIONS (Table 6)",
    quote: "Coadministration is contraindicated with, but not limited to, the following drugs",
    labelExample: "Antineoplastics Apalutamide, encorafenib, irinotecan, ivosidenib",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8",
  },
  {
    id: "atazanavir+ivosidenib",
    labelDrugId: "atazanavir",
    otherId: "ivosidenib",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Reyataz (atazanavir)",
    labelSection: "4 CONTRAINDICATIONS (Table 6)",
    quote: "Coadministration is contraindicated with, but not limited to, the following drugs",
    labelExample: "Antineoplastics Apalutamide, encorafenib, irinotecan, ivosidenib",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8",
  },
  {
    id: "atazanavir+dihydroergotamine",
    labelDrugId: "atazanavir",
    otherId: "dihydroergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Reyataz (atazanavir)",
    labelSection: "4 CONTRAINDICATIONS (Table 6)",
    quote: "Coadministration is contraindicated with, but not limited to, the following drugs",
    labelExample: "Ergot Derivatives Dihydroergotamine, ergonovine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8",
  },
  {
    id: "atazanavir+ergotamine",
    labelDrugId: "atazanavir",
    otherId: "ergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Reyataz (atazanavir)",
    labelSection: "4 CONTRAINDICATIONS (Table 6)",
    quote: "Coadministration is contraindicated with, but not limited to, the following drugs",
    labelExample: "Ergot Derivatives Dihydroergotamine, ergonovine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8",
  },
  {
    id: "atazanavir+methylergonovine",
    labelDrugId: "atazanavir",
    otherId: "methylergonovine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Reyataz (atazanavir)",
    labelSection: "4 CONTRAINDICATIONS (Table 6)",
    quote: "Coadministration is contraindicated with, but not limited to, the following drugs",
    labelExample: "Ergot Derivatives Dihydroergotamine, ergonovine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8",
  },
  {
    id: "atazanavir+glecaprevir-pibrentasvir",
    labelDrugId: "atazanavir",
    otherId: "glecaprevir-pibrentasvir",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Reyataz (atazanavir)",
    labelSection: "4 CONTRAINDICATIONS (Table 6)",
    quote: "Coadministration is contraindicated with, but not limited to, the following drugs",
    labelExample: "Hepatitis C Direct-Acting Antivirals Elbasvir/grazoprevir; glecaprevir/pibrentasvir",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8",
  },
  {
    id: "atazanavir+st-johns-wort",
    labelDrugId: "atazanavir",
    otherId: "st-johns-wort",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Reyataz (atazanavir)",
    labelSection: "4 CONTRAINDICATIONS (Table 6)",
    quote: "Coadministration is contraindicated with, but not limited to, the following drugs",
    labelExample: "St. John’s wort",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8",
  },
  {
    id: "atazanavir+sildenafil-pah",
    labelDrugId: "atazanavir",
    otherId: "sildenafil-pah",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Reyataz (atazanavir)",
    labelSection: "4 CONTRAINDICATIONS (Table 6)",
    quote: "Coadministration is contraindicated with, but not limited to, the following drugs",
    labelExample: "Sildenafil b when dosed as REVATIO ® for the treatment of pulmonary arterial hypertension",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8",
  },
  {
    id: "atazanavir+nevirapine",
    labelDrugId: "atazanavir",
    otherId: "nevirapine",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Reyataz (atazanavir)",
    labelSection: "4 CONTRAINDICATIONS (Table 6)",
    quote: "Coadministration is contraindicated with, but not limited to, the following drugs",
    labelExample: "Non-nucleoside Reverse Transcriptase Inhibitors Nevirapine",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8",
  },
  {
    id: "atazanavir-cobicistat+dronedarone",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "dronedarone",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "Antiarrhythmics dronedarone",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },
  {
    id: "atazanavir-cobicistat+carbamazepine",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "carbamazepine",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "Anticonvulsants carbamazepine, phenobarbital, phenytoin",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },
  {
    id: "atazanavir-cobicistat+phenobarbital",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "phenobarbital",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "Anticonvulsants carbamazepine, phenobarbital, phenytoin",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },
  {
    id: "atazanavir-cobicistat+phenytoin",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "phenytoin",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "Anticonvulsants carbamazepine, phenobarbital, phenytoin",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },
  {
    id: "atazanavir-cobicistat+rifampin",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "rifampin",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "Antimycobacterials rifampin",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },
  {
    id: "atazanavir-cobicistat+apalutamide",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "apalutamide",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "Antineoplastics apalutamide, encorafenib, irinotecan, ivosidenib",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },
  {
    id: "atazanavir-cobicistat+encorafenib",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "encorafenib",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "Antineoplastics apalutamide, encorafenib, irinotecan, ivosidenib",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },
  {
    id: "atazanavir-cobicistat+ivosidenib",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "ivosidenib",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "Antineoplastics apalutamide, encorafenib, irinotecan, ivosidenib",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },
  {
    id: "atazanavir-cobicistat+dihydroergotamine",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "dihydroergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "Ergot Derivatives dihydroergotamine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },
  {
    id: "atazanavir-cobicistat+ergotamine",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "ergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "Ergot Derivatives dihydroergotamine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },
  {
    id: "atazanavir-cobicistat+methylergonovine",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "methylergonovine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "Ergot Derivatives dihydroergotamine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },
  {
    id: "atazanavir-cobicistat+glecaprevir-pibrentasvir",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "glecaprevir-pibrentasvir",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "Hepatitis C Direct-Acting Antivirals elbasvir/grazoprevir; glecaprevir/pibrentasvir",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },
  {
    id: "atazanavir-cobicistat+st-johns-wort",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "st-johns-wort",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "St. John’s wort",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },
  {
    id: "atazanavir-cobicistat+ethinyl-estradiol",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "ethinyl-estradiol",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "drospirenone/ethinyl estradiol",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },
  {
    id: "atazanavir-cobicistat+nevirapine",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "nevirapine",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "Non-nucleoside Reverse Transcriptase Inhibitor nevirapine",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },
  {
    id: "atazanavir-cobicistat+sildenafil-pah",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "sildenafil-pah",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "sildenafil a when administered for the treatment of pulmonary arterial hypertension",
    basis: "named",
    origin: "wave3",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },

  // ── No CYP finding to hold. The partner catalog row has no enzyme role the
  // engine uses, so there is nothing to raise. These pins omit enzyme and kind
  // and emit a standalone contraindicated finding. Quotes, section, and
  // DailyMed links are copied from the wave-3 gold set (retrieved 2026-10-02).
  // Irinotecan is UGT1A1, not a CYP. Elbasvir/grazoprevir and drospirenone are
  // not given a CYP grade here.
  {
    id: "darunavir+grazoprevir-elbasvir",
    labelDrugId: "darunavir",
    otherId: "grazoprevir-elbasvir",
    labelDrug: "Prezista (darunavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of these drugs and other contraindicated drugs (which may lead to reduced efficacy of darunavir) are listed below",
    labelExample: "Hepatitis C direct acting antiviral: elbasvir/grazoprevir",
    basis: "named",
    origin: "no-enzyme",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=814301f9-c990-46a5-b481-2879a521a16f",
  },
  {
    id: "darunavir-cobicistat+grazoprevir-elbasvir",
    labelDrugId: "darunavir-cobicistat",
    otherId: "grazoprevir-elbasvir",
    labelDrug: "Prezcobix (darunavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Examples of drugs that are contraindicated for co-administration with PREZCOBIX",
    labelExample: "Hepatitis C direct acting antiviral: elbasvir/grazoprevir",
    basis: "named",
    origin: "no-enzyme",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9c38fdb6-d0ba-4f16-a0e3-85d9ec334d9f",
  },
  {
    id: "atazanavir+grazoprevir-elbasvir",
    labelDrugId: "atazanavir",
    otherId: "grazoprevir-elbasvir",
    labelDrug: "Reyataz (atazanavir)",
    labelSection: "4 CONTRAINDICATIONS (Table 6)",
    quote: "Coadministration is contraindicated with, but not limited to, the following drugs",
    labelExample: "Hepatitis C Direct-Acting Antivirals Elbasvir/grazoprevir; glecaprevir/pibrentasvir",
    basis: "named",
    origin: "no-enzyme",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8",
  },
  {
    id: "atazanavir-cobicistat+grazoprevir-elbasvir",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "grazoprevir-elbasvir",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "Hepatitis C Direct-Acting Antivirals elbasvir/grazoprevir; glecaprevir/pibrentasvir",
    basis: "named",
    origin: "no-enzyme",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },
  {
    id: "atazanavir+irinotecan",
    labelDrugId: "atazanavir",
    otherId: "irinotecan",
    labelDrug: "Reyataz (atazanavir)",
    labelSection: "4 CONTRAINDICATIONS (Table 6)",
    quote: "Coadministration is contraindicated with, but not limited to, the following drugs",
    labelExample: "Antineoplastics Apalutamide, encorafenib, irinotecan, ivosidenib",
    basis: "named",
    origin: "no-enzyme",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=165cff62-b284-4a27-a65d-9ec8a5bfcdd8",
  },
  {
    id: "atazanavir-cobicistat+irinotecan",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "irinotecan",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "Antineoplastics apalutamide, encorafenib, irinotecan, ivosidenib",
    basis: "named",
    origin: "no-enzyme",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },
  {
    id: "atazanavir-cobicistat+drospirenone",
    labelDrugId: "atazanavir-cobicistat",
    otherId: "drospirenone",
    labelDrug: "Evotaz (atazanavir/cobicistat)",
    labelSection: "4 CONTRAINDICATIONS (Table 1)",
    quote: "The concomitant use of EVOTAZ and the following drugs in Table 1, are contraindicated",
    labelExample: "drospirenone/ethinyl estradiol",
    basis: "named",
    origin: "no-enzyme",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=83db29d7-5d85-49d6-8cb6-740473365cf8",
  },

  // ── Wave 4 (PR #86, feat/label-gold-wave4 @ 5912f77). Quotes, section, and
  // DailyMed links are copied byte-for-byte from that gold set (retrieved
  // 2026-10-02). These pairs already produce an enzyme finding below
  // contraindicated. The pin holds that finding. It does not add a CYP grade.

  {
    id: "clarithromycin+ergotamine",
    labelDrugId: "clarithromycin",
    otherId: "ergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Clarithromycin tablets",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Concomitant administration of clarithromycin and ergotamine or dihydroergotamine is contraindicated",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9d5848f0-e9f0-4112-a7ca-bcc8ea2e69c6",
  },
  {
    id: "clarithromycin+dihydroergotamine",
    labelDrugId: "clarithromycin",
    otherId: "dihydroergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Clarithromycin tablets",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Concomitant administration of clarithromycin and ergotamine or dihydroergotamine is contraindicated",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=9d5848f0-e9f0-4112-a7ca-bcc8ea2e69c6",
  },
  {
    id: "itraconazole+methadone",
    labelDrugId: "itraconazole",
    otherId: "methadone",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Sporanox (itraconazole)",
    labelSection: "CONTRAINDICATIONS",
    quote: "Coadministration of a number of CYP3A4 substrates are contraindicated with SPORANOX®.",
    labelExample: "methadone",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0",
  },
  {
    id: "itraconazole+disopyramide",
    labelDrugId: "itraconazole",
    otherId: "disopyramide",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Sporanox (itraconazole)",
    labelSection: "CONTRAINDICATIONS",
    quote: "Coadministration of a number of CYP3A4 substrates are contraindicated with SPORANOX®.",
    labelExample: "disopyramide",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0",
  },
  {
    id: "itraconazole+dronedarone",
    labelDrugId: "itraconazole",
    otherId: "dronedarone",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Sporanox (itraconazole)",
    labelSection: "CONTRAINDICATIONS",
    quote: "Coadministration of a number of CYP3A4 substrates are contraindicated with SPORANOX®.",
    labelExample: "dronedarone",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0",
  },
  {
    id: "itraconazole+quinidine",
    labelDrugId: "itraconazole",
    otherId: "quinidine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Sporanox (itraconazole)",
    labelSection: "CONTRAINDICATIONS",
    quote: "Coadministration of a number of CYP3A4 substrates are contraindicated with SPORANOX®.",
    labelExample: "quinidine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0",
  },
  {
    id: "itraconazole+isavuconazole",
    labelDrugId: "itraconazole",
    otherId: "isavuconazole",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Sporanox (itraconazole)",
    labelSection: "CONTRAINDICATIONS",
    quote: "Coadministration of a number of CYP3A4 substrates are contraindicated with SPORANOX®.",
    labelExample: "isavuconazole",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0",
  },
  {
    id: "itraconazole+dihydroergotamine",
    labelDrugId: "itraconazole",
    otherId: "dihydroergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Sporanox (itraconazole)",
    labelSection: "CONTRAINDICATIONS",
    quote: "Coadministration of a number of CYP3A4 substrates are contraindicated with SPORANOX®.",
    labelExample: "dihydroergotamine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0",
  },
  {
    id: "itraconazole+ergotamine",
    labelDrugId: "itraconazole",
    otherId: "ergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Sporanox (itraconazole)",
    labelSection: "CONTRAINDICATIONS",
    quote: "Coadministration of a number of CYP3A4 substrates are contraindicated with SPORANOX®.",
    labelExample: "ergotamine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0",
  },
  {
    id: "itraconazole+methylergonovine",
    labelDrugId: "itraconazole",
    otherId: "methylergonovine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Sporanox (itraconazole)",
    labelSection: "CONTRAINDICATIONS",
    quote: "Coadministration of a number of CYP3A4 substrates are contraindicated with SPORANOX®.",
    labelExample: "methylergonovine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0",
  },
  {
    id: "itraconazole+avanafil",
    labelDrugId: "itraconazole",
    otherId: "avanafil",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Sporanox (itraconazole)",
    labelSection: "CONTRAINDICATIONS",
    quote: "Coadministration of a number of CYP3A4 substrates are contraindicated with SPORANOX®.",
    labelExample: "avanafil",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0",
  },
  {
    id: "itraconazole+ticagrelor",
    labelDrugId: "itraconazole",
    otherId: "ticagrelor",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Sporanox (itraconazole)",
    labelSection: "CONTRAINDICATIONS",
    quote: "Coadministration of a number of CYP3A4 substrates are contraindicated with SPORANOX®.",
    labelExample: "ticagrelor",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0",
  },
  {
    id: "posaconazole+quinidine",
    labelDrugId: "posaconazole",
    otherId: "quinidine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Noxafil (posaconazole)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Noxafil is contraindicated with CYP3A4 substrates that prolong the QT interval.",
    labelExample: "pimozide and quinidine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b073b082-7b57-4423-8c06-4fd4263d6f84",
  },
  {
    id: "posaconazole+atorvastatin",
    labelDrugId: "posaconazole",
    otherId: "atorvastatin",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Noxafil (posaconazole)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Coadministration with the HMG-CoA reductase inhibitors that are primarily metabolized through CYP3A4 (e.g., atorvastatin, lovastatin, and simvastatin) is contraindicated",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b073b082-7b57-4423-8c06-4fd4263d6f84",
  },
  {
    id: "posaconazole+ergotamine",
    labelDrugId: "posaconazole",
    otherId: "ergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Noxafil (posaconazole)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Coadministration of Noxafil with the following drugs is contraindicated",
    labelExample: "ergot alkaloids (ergotamine and dihydroergotamine)",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b073b082-7b57-4423-8c06-4fd4263d6f84",
  },
  {
    id: "posaconazole+dihydroergotamine",
    labelDrugId: "posaconazole",
    otherId: "dihydroergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Noxafil (posaconazole)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "Coadministration of Noxafil with the following drugs is contraindicated",
    labelExample: "ergot alkaloids (ergotamine and dihydroergotamine)",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b073b082-7b57-4423-8c06-4fd4263d6f84",
  },
  {
    id: "ritonavir+amiodarone",
    labelDrugId: "ritonavir",
    otherId: "amiodarone",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Norvir (ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "NORVIR is contraindicated with drugs that are highly dependent on CYP3A for clearance",
    labelExample: "Antiarrhythmics: amiodarone, dronedarone, flecainide, propafenone, quinidine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3",
  },
  {
    id: "ritonavir+dronedarone",
    labelDrugId: "ritonavir",
    otherId: "dronedarone",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Norvir (ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "NORVIR is contraindicated with drugs that are highly dependent on CYP3A for clearance",
    labelExample: "Antiarrhythmics: amiodarone, dronedarone, flecainide, propafenone, quinidine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3",
  },
  {
    id: "ritonavir+flecainide",
    labelDrugId: "ritonavir",
    otherId: "flecainide",
    enzyme: "CYP2D6",
    kind: "inhibitor",
    labelDrug: "Norvir (ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "NORVIR is contraindicated with drugs that are highly dependent on CYP3A for clearance",
    labelExample: "Antiarrhythmics: amiodarone, dronedarone, flecainide, propafenone, quinidine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3",
  },
  {
    id: "ritonavir+propafenone",
    labelDrugId: "ritonavir",
    otherId: "propafenone",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Norvir (ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "NORVIR is contraindicated with drugs that are highly dependent on CYP3A for clearance",
    labelExample: "Antiarrhythmics: amiodarone, dronedarone, flecainide, propafenone, quinidine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3",
  },
  {
    id: "ritonavir+quinidine",
    labelDrugId: "ritonavir",
    otherId: "quinidine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Norvir (ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "NORVIR is contraindicated with drugs that are highly dependent on CYP3A for clearance",
    labelExample: "Antiarrhythmics: amiodarone, dronedarone, flecainide, propafenone, quinidine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3",
  },
  {
    id: "ritonavir+dihydroergotamine",
    labelDrugId: "ritonavir",
    otherId: "dihydroergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Norvir (ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "NORVIR is contraindicated with drugs that are highly dependent on CYP3A for clearance",
    labelExample: "Ergot Derivatives: dihydroergotamine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3",
  },
  {
    id: "ritonavir+methylergonovine",
    labelDrugId: "ritonavir",
    otherId: "methylergonovine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Norvir (ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "NORVIR is contraindicated with drugs that are highly dependent on CYP3A for clearance",
    labelExample: "Ergot Derivatives: dihydroergotamine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3",
  },
  {
    id: "ritonavir+suzetrigine",
    labelDrugId: "ritonavir",
    otherId: "suzetrigine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Norvir (ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "NORVIR is contraindicated with drugs that are highly dependent on CYP3A for clearance",
    labelExample: "Non-opioid Analgesic (selective blocker of Nav1.8 sodium channels): suzetrigine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3",
  },
  {
    id: "ritonavir+sildenafil-pah",
    labelDrugId: "ritonavir",
    otherId: "sildenafil-pah",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Norvir (ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "NORVIR is contraindicated with drugs that are highly dependent on CYP3A for clearance",
    labelExample: "PDE5 Inhibitor: sildenafil (Revatio®) when used for the treatment of pulmonary arterial hypertension",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3",
  },
  {
    id: "ritonavir+apalutamide",
    labelDrugId: "ritonavir",
    otherId: "apalutamide",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Norvir (ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "NORVIR is contraindicated with drugs that are potent CYP3A inducers",
    labelExample: "Anticancer Agents: apalutamide",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3",
  },
  {
    id: "ritonavir+st-johns-wort",
    labelDrugId: "ritonavir",
    otherId: "st-johns-wort",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Norvir (ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "NORVIR is contraindicated with drugs that are potent CYP3A inducers",
    labelExample: "St. John's Wort (hypericum perforatum)",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2849298e-de6e-47bb-8194-56e075b33fc3",
  },
  {
    id: "paxlovid+amiodarone",
    labelDrugId: "paxlovid",
    otherId: "amiodarone",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A",
    labelExample: "Antiarrhythmic: amiodarone, dronedarone, flecainide, propafenone, quinidine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+dronedarone",
    labelDrugId: "paxlovid",
    otherId: "dronedarone",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A",
    labelExample: "Antiarrhythmic: amiodarone, dronedarone, flecainide, propafenone, quinidine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+propafenone",
    labelDrugId: "paxlovid",
    otherId: "propafenone",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A",
    labelExample: "Antiarrhythmic: amiodarone, dronedarone, flecainide, propafenone, quinidine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+quinidine",
    labelDrugId: "paxlovid",
    otherId: "quinidine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A",
    labelExample: "Antiarrhythmic: amiodarone, dronedarone, flecainide, propafenone, quinidine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+dihydroergotamine",
    labelDrugId: "paxlovid",
    otherId: "dihydroergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A",
    labelExample: "Ergot derivatives: dihydroergotamine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+ergotamine",
    labelDrugId: "paxlovid",
    otherId: "ergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A",
    labelExample: "Ergot derivatives: dihydroergotamine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+methylergonovine",
    labelDrugId: "paxlovid",
    otherId: "methylergonovine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A",
    labelExample: "Ergot derivatives: dihydroergotamine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+suzetrigine",
    labelDrugId: "paxlovid",
    otherId: "suzetrigine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A",
    labelExample: "Non-opioid analgesic (selective blocker of Nav1.8 sodium channels): suzetrigine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+sildenafil-pah",
    labelDrugId: "paxlovid",
    otherId: "sildenafil-pah",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A",
    labelExample: "PDE5 inhibitor: sildenafil (Revatio®) when used for pulmonary arterial hypertension (PAH)",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+apalutamide",
    labelDrugId: "paxlovid",
    otherId: "apalutamide",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A … and drugs that are strong CYP3A inducers",
    labelExample: "Anticancer drugs: apalutamide, enzalutamide",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+enzalutamide",
    labelDrugId: "paxlovid",
    otherId: "enzalutamide",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A … and drugs that are strong CYP3A inducers",
    labelExample: "Anticancer drugs: apalutamide, enzalutamide",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+carbamazepine",
    labelDrugId: "paxlovid",
    otherId: "carbamazepine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A … and drugs that are strong CYP3A inducers",
    labelExample: "Anticonvulsant: carbamazepine, phenobarbital, primidone, phenytoin",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+lumacaftor-ivacaftor",
    labelDrugId: "paxlovid",
    otherId: "lumacaftor-ivacaftor",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A … and drugs that are strong CYP3A inducers",
    labelExample: "Cystic fibrosis transmembrane conductance regulator potentiators: lumacaftor/ivacaftor",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "lopinavir+dronedarone",
    labelDrugId: "lopinavir",
    otherId: "dronedarone",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Kaletra (lopinavir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "KALETRA is contraindicated with drugs that are highly dependent on CYP3A for clearance",
    labelExample: "Antiarrhythmic: dronedarone",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3",
  },
  {
    id: "lopinavir+dihydroergotamine",
    labelDrugId: "lopinavir",
    otherId: "dihydroergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Kaletra (lopinavir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "KALETRA is contraindicated with drugs that are highly dependent on CYP3A for clearance",
    labelExample: "Ergot Derivatives: dihydroergotamine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3",
  },
  {
    id: "lopinavir+ergotamine",
    labelDrugId: "lopinavir",
    otherId: "ergotamine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Kaletra (lopinavir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "KALETRA is contraindicated with drugs that are highly dependent on CYP3A for clearance",
    labelExample: "Ergot Derivatives: dihydroergotamine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3",
  },
  {
    id: "lopinavir+methylergonovine",
    labelDrugId: "lopinavir",
    otherId: "methylergonovine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Kaletra (lopinavir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "KALETRA is contraindicated with drugs that are highly dependent on CYP3A for clearance",
    labelExample: "Ergot Derivatives: dihydroergotamine, ergotamine, methylergonovine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3",
  },
  {
    id: "lopinavir+suzetrigine",
    labelDrugId: "lopinavir",
    otherId: "suzetrigine",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Kaletra (lopinavir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "KALETRA is contraindicated with drugs that are highly dependent on CYP3A for clearance",
    labelExample: "Non-opioid Analgesic (selective blocker of Nav1.8 sodium channels): suzetrigine",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3",
  },
  {
    id: "lopinavir+sildenafil-pah",
    labelDrugId: "lopinavir",
    otherId: "sildenafil-pah",
    enzyme: "CYP3A4",
    kind: "inhibitor",
    labelDrug: "Kaletra (lopinavir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "KALETRA is contraindicated with drugs that are highly dependent on CYP3A for clearance",
    labelExample: "PDE5 Inhibitor: sildenafil (Revatio®) when used for the treatment of pulmonary arterial hypertension",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3",
  },
  {
    id: "lopinavir+apalutamide",
    labelDrugId: "lopinavir",
    otherId: "apalutamide",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Kaletra (lopinavir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "KALETRA is contraindicated with drugs that are potent CYP3A inducers",
    labelExample: "Anticancer Agents: apalutamide",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3",
  },
  {
    id: "lopinavir+rifampin",
    labelDrugId: "lopinavir",
    otherId: "rifampin",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Kaletra (lopinavir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "KALETRA is contraindicated with drugs that are potent CYP3A inducers",
    labelExample: "Antimycobacterial: rifampin",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3",
  },
  {
    id: "lopinavir+st-johns-wort",
    labelDrugId: "lopinavir",
    otherId: "st-johns-wort",
    enzyme: "CYP3A4",
    kind: "inducer",
    labelDrug: "Kaletra (lopinavir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "KALETRA is contraindicated with drugs that are potent CYP3A inducers",
    labelExample: "Herbal Products: St. John's Wort (hypericum perforatum)",
    basis: "named",
    origin: "wave4",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3",
  },

  // Wave 4 pairs with no enzyme finding to hold. Standalone contraindicated
  // findings (label-ci-standalone). Enzyme and kind are omitted on purpose:
  // itraconazole has no finding with dofetilide or irinotecan; Paxlovid has
  // no finding with flecainide (CYP2D6 only), phenytoin, or rifapentine, and
  // only a washout clock (not an enzyme finding) with phenobarbital,
  // primidone, rifampin, and St. John's wort; Kaletra has no finding with
  // elbasvir/grazoprevir. Do not invent a CYP grade for these.

  {
    id: "itraconazole+dofetilide",
    labelDrugId: "itraconazole",
    otherId: "dofetilide",
    labelDrug: "Sporanox (itraconazole)",
    labelSection: "CONTRAINDICATIONS",
    quote: "Coadministration of a number of CYP3A4 substrates are contraindicated with SPORANOX®.",
    labelExample: "dofetilide",
    basis: "named",
    origin: "no-enzyme",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0",
  },
  {
    id: "itraconazole+irinotecan",
    labelDrugId: "itraconazole",
    otherId: "irinotecan",
    labelDrug: "Sporanox (itraconazole)",
    labelSection: "CONTRAINDICATIONS",
    quote: "Coadministration of a number of CYP3A4 substrates are contraindicated with SPORANOX®.",
    labelExample: "irinotecan",
    basis: "named",
    origin: "no-enzyme",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=a4d555fa-787c-40fb-bb7d-b0d4f7318fd0",
  },
  {
    id: "paxlovid+flecainide",
    labelDrugId: "paxlovid",
    otherId: "flecainide",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A",
    labelExample: "Antiarrhythmic: amiodarone, dronedarone, flecainide, propafenone, quinidine",
    basis: "named",
    origin: "no-enzyme",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+phenobarbital",
    labelDrugId: "paxlovid",
    otherId: "phenobarbital",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A … and drugs that are strong CYP3A inducers",
    labelExample: "Anticonvulsant: carbamazepine, phenobarbital, primidone, phenytoin",
    basis: "named",
    origin: "no-enzyme",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+primidone",
    labelDrugId: "paxlovid",
    otherId: "primidone",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A … and drugs that are strong CYP3A inducers",
    labelExample: "Anticonvulsant: carbamazepine, phenobarbital, primidone, phenytoin",
    basis: "named",
    origin: "no-enzyme",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+phenytoin",
    labelDrugId: "paxlovid",
    otherId: "phenytoin",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A … and drugs that are strong CYP3A inducers",
    labelExample: "Anticonvulsant: carbamazepine, phenobarbital, primidone, phenytoin",
    basis: "named",
    origin: "no-enzyme",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+rifampin",
    labelDrugId: "paxlovid",
    otherId: "rifampin",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A … and drugs that are strong CYP3A inducers",
    labelExample: "Antimycobacterials: rifampin, rifapentine",
    basis: "named",
    origin: "no-enzyme",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+rifapentine",
    labelDrugId: "paxlovid",
    otherId: "rifapentine",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A … and drugs that are strong CYP3A inducers",
    labelExample: "Antimycobacterials: rifampin, rifapentine",
    basis: "named",
    origin: "no-enzyme",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "paxlovid+st-johns-wort",
    labelDrugId: "paxlovid",
    otherId: "st-johns-wort",
    labelDrug: "Paxlovid (nirmatrelvir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "PAXLOVID is contraindicated with drugs that are primarily metabolized by CYP3A … and drugs that are strong CYP3A inducers",
    labelExample: "Herbal products: St. John's Wort (hypericum perforatum)",
    basis: "named",
    origin: "no-enzyme",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8a99d6d6-fd9e-45bb-b1bf-48c7f761232a",
  },
  {
    id: "lopinavir+grazoprevir-elbasvir",
    labelDrugId: "lopinavir",
    otherId: "grazoprevir-elbasvir",
    labelDrug: "Kaletra (lopinavir/ritonavir)",
    labelSection: "4 CONTRAINDICATIONS",
    quote: "KALETRA is contraindicated with drugs that are highly dependent on CYP3A for clearance",
    labelExample: "Hepatitis C direct acting antiviral: elbasvir/grazoprevir",
    basis: "named",
    origin: "no-enzyme",
    retrieved: "2026-10-02",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=8290add3-4449-4e58-6c97-8fe1eec972e3",
  },
];

export const LABEL_CONTRAINDICATED_TAG = "label-contraindicated";

const BY_PAIR = new Map<string, LabelContraindication>();
for (const r of LABEL_CONTRAINDICATIONS) {
  BY_PAIR.set([r.labelDrugId, r.otherId].sort().join("|"), r);
}

/** Pin for an unordered pair of catalog ids, if the label contraindicates it. */
export function labelContraindicationFor(a: string, b: string): LabelContraindication | undefined {
  return BY_PAIR.get([a, b].sort().join("|"));
}

export function labelContraindicationById(id: string): LabelContraindication | undefined {
  return LABEL_CONTRAINDICATIONS.find((r) => r.id === id);
}

/** Plain sentence appended to the pinned finding's clinical text. */
export function labelPinSentence(r: LabelContraindication): string {
  if (!r.enzyme) {
    return `The ${r.labelDrug} label lists this combination under Contraindications, so this desk shows it as Avoid together. This pair has no CYP finding; the label is the reason.`;
  }
  return `The ${r.labelDrug} label lists this combination under Contraindications, so this desk shows it as Avoid together even where the enzyme grades alone would read lower.`;
}
