/**
 * FDA Drug Development and Drug Interactions reference: a typed transcription.
 *
 * Source (primary; Table 1 transcribed here):
 *   "For Healthcare Professionals | FDA's Examples of Drugs that Interact with
 *   CYP Enzymes and Transporter Systems", Table 1 "CYP Enzyme- and Transporter
 *   System-Based Clinical Substrates, Inhibitors, or Inducers".
 *   https://www.fda.gov/drugs/drug-interactions-labeling/healthcare-professionals-fdas-examples-drugs-interact-cyp-enzymes-and-transporter-systems
 *   Page "Content current as of": 05/29/2026.
 *
 * Companion page (checked, not transcribed): "Drug Development and Drug
 *   Interactions | Table of Substrates, Inhibitors and Inducers"
 *   https://www.fda.gov/drugs/drug-interactions-labeling/drug-development-and-drug-interactions-table-substrates-inhibitors-and-inducers
 *   Page "Content current as of": 06/05/2023. It now carries in vitro probes and
 *   clinical *index* drugs only; the clinical examples live in Table 1 above.
 *
 * Retrieved: 2026-09-26. Live page read via WebFetch; rows parsed from the
 *   page HTML (Wayback snapshot 2026-09-23 of the same URL, because fda.gov
 *   returns 401 to scripted curl) and cross-checked against the live render.
 *
 * Scope: only targets the FirstPass catalog models (see ENZYMES in ../types):
 *   CYP1A2, CYP2B6, CYP2C8, CYP2C9, CYP2C19, CYP2D6, CYP3A (FDA "3A"; mapped
 *   to our CYP3A4 key), and P-gp. FDA lists no CYP2E1 examples. Other
 *   transporters (BCRP, OATP, OAT, OCT, MATE) are omitted. FDA grades
 *   transporter roles without a potency class, so P-gp rows have fdaClass null.
 *
 * Drug names are written exactly as FDA writes them (including FDA's own
 * capitalization, e.g. "Loperamide"); footnote superscripts are split into
 * `footnotes`. `cell` keeps FDA's verbatim cell text for audit.
 *
 * FDA: "the examples in Table 1 are a guide and not considered a comprehensive
 * list". Absence from this table is NOT evidence a drug lacks a role.
 *
 * Educational reference data. Not FDA-cleared; not for clinical decisions.
 * GENERATED from the FDA HTML table; do not hand-edit rows. Re-transcribe.
 */
import type { Enzyme } from "../types";

export const FDA_DDI_SOURCE = {
  title:
    "For Healthcare Professionals | FDA's Examples of Drugs that Interact with CYP Enzymes and Transporter Systems (Table 1)",
  url: "https://www.fda.gov/drugs/drug-interactions-labeling/healthcare-professionals-fdas-examples-drugs-interact-cyp-enzymes-and-transporter-systems",
  companionUrl:
    "https://www.fda.gov/drugs/drug-interactions-labeling/drug-development-and-drug-interactions-table-substrates-inhibitors-and-inducers",
  contentCurrentAsOf: "2026-05-29",
  companionContentCurrentAsOf: "2023-06-05",
  retrieved: "2026-09-26",
} as const;

/** Catalog enzyme keys this reference covers (FDA "3A" is mapped to CYP3A4). */
export type FdaTarget = Extract<Enzyme, "CYP1A2" | "CYP2B6" | "CYP2C8" | "CYP2C9" | "CYP2C19" | "CYP2D6" | "CYP3A4" | "P-gp">;

/** Targets covered by this transcription (runtime list for FdaTarget). */
export const FDA_TARGETS: readonly FdaTarget[] = ["CYP1A2", "CYP2B6", "CYP2C8", "CYP2C9", "CYP2C19", "CYP2D6", "CYP3A4", "P-gp"];

export type FdaPerpetratorClass = "strong" | "moderate" | "weak";
export type FdaSubstrateClass = "sensitive" | "moderate-sensitive";

export type FdaDdiEntry =
  | {
      drug: string;
      target: FdaTarget;
      kind: "inhibitor" | "inducer";
      /** FDA potency class; null for transporter (P-gp) rows, which FDA does not grade. */
      fdaClass: FdaPerpetratorClass | null;
      cell: string;
      footnotes: number[];
    }
  | {
      drug: string;
      target: FdaTarget;
      kind: "substrate";
      fdaClass: FdaSubstrateClass | null;
      cell: string;
      footnotes: number[];
    };

/** FDA Table 1 footnotes referenced by the rows below. Footnotes that quote exposure amounts are not reproduced here (see source). */
export const FDA_DDI_FOOTNOTES: Record<number, string> = {
  1: "These drugs are active moieties of their corresponding pro-drugs, adefovir dipivoxil, oseltamivir, tenofovir alafenamide fumarate (TAF), and tenofovir disoproxil fumarate (TDF). Those pro-drugs are substrates of P-gp.",
  2: "Bupropion itself is not a sensitive substrate. It is metabolized by multiple enzymes including CYP2B6 that is only responsible for the formation of hydroxybupropion, an active metabolite. Thus, the considerations of drug interactions with CYP2B6 modulators should take into account plasma concentration changes of both buproprion and hydroxybupropion.",
  3: "Listed based on pharmacogenetic studies.",
  4: "Exposure-condition caveat (FDA footnote 4); wording not reproduced here, see the source page.",
  5: "The classification is based on studies conducted with intravenously administered conivaptan.",
  6: "Usually administered to patients in combination with ritonavir, a strong CYP3A inhibitor.",
  7: "Diltiazem increased AUC of certain sensitive CYP3A substrates (e.g., buspirone) more than 5-fold.",
  8: "Fluvoxamine increased the AUC of certain sensitive CYP3A substrates more than 2-fold (e.g., increased the AUC of buspirone 2.35-fold)",
  9: "Paraphrase: the grapefruit juice effect varies widely by brand and preparation; FDA notes it can classify as a strong CYP3A inhibitor with some preparations and more commonly as a moderate one.",
  10: "Based on PBPK simulation",
  11: "S-lansoprazole is a sensitive substrate in CYP2C19 extensive metabolizer subjects.",
  12: "Exposure-condition caveat (FDA footnote 12); wording not reproduced here, see the source page.",
  14: "Ritonavir is approved for use in combination with other anti-HIV or anti-HCV drugs. Caution should be used when extrapolating the observed effect of ritonavir alone to the effect of anti-HIV or anti-HCV combination regimens on CYP3A activities.",
  15: "Exposure-condition caveat (FDA footnote 15); wording not reproduced here, see the source page.",
  16: "Exposure-condition caveat (FDA footnote 16); wording not reproduced here, see the source page.",
  17: "Intravenously administered rolapitant does not inhibit BCRP and P-gp.",
  18: "The effect of St. John’s wort varies widely and is preparation dependent.",
  19: "S-warfarin",
  20: "Ciprofloxacin is generally classified a moderate CYP 1A2 inhibitor based on totality of evidence; however, it can sometimes behave like a strong inhibitor (i.e., increase AUC more than 5-fold) when it interacts with certain CYP 1A2 substrates that are considered highly sensitive (e.g., tizanidine).",
  21: "Selexipag is a prodrug. it is the selexipag active metabolite ACT-333679 that is a sensitive substrate of CYP2C8. Selexipag and ACT-333679 are also substrates of OATP1B transporter",
};

export const FDA_DDI_TABLE: readonly FdaDdiEntry[] = [
  { drug: "abiraterone", target: "CYP2D6", kind: "inhibitor", fdaClass: "moderate", cell: "2D6 moderate inhibitor", footnotes: [] },
  { drug: "acyclovir", target: "CYP1A2", kind: "inhibitor", fdaClass: "weak", cell: "1A2 weak inhibitor", footnotes: [] },
  { drug: "adagrasib", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "alfentanil", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "allopurinol", target: "CYP1A2", kind: "inhibitor", fdaClass: "weak", cell: "1A2 weak inhibitor", footnotes: [] },
  { drug: "alosetron", target: "CYP1A2", kind: "substrate", fdaClass: "sensitive", cell: "1A2 sensitive substrate", footnotes: [] },
  { drug: "alprazolam", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderate sensitive substrate", footnotes: [] },
  { drug: "amiodarone", target: "CYP2C9", kind: "inhibitor", fdaClass: "moderate", cell: "2C9 moderate inhibitor", footnotes: [] },
  { drug: "amiodarone", target: "CYP2D6", kind: "inhibitor", fdaClass: "weak", cell: "2D6; 3A weak inhibitor", footnotes: [] },
  { drug: "amiodarone", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "2D6; 3A weak inhibitor", footnotes: [] },
  { drug: "amiodarone", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp inhibitor", footnotes: [] },
  { drug: "apalutamide", target: "CYP3A4", kind: "inducer", fdaClass: "strong", cell: "3A strong inducer", footnotes: [] },
  { drug: "apalutamide", target: "CYP2C19", kind: "inducer", fdaClass: "moderate", cell: "2C19 moderate inducer", footnotes: [] },
  { drug: "apalutamide", target: "CYP2C9", kind: "inducer", fdaClass: "weak", cell: "2C9 weak inducer", footnotes: [] },
  { drug: "aprepitant", target: "CYP2C9", kind: "inducer", fdaClass: "weak", cell: "2C9 weak inducer", footnotes: [] },
  { drug: "aprepitant", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderate sensitive substrate", footnotes: [] },
  { drug: "aprepitant", target: "CYP3A4", kind: "inhibitor", fdaClass: "moderate", cell: "3A moderate inhibitor", footnotes: [] },
  { drug: "armodafinil", target: "CYP3A4", kind: "inducer", fdaClass: "weak", cell: "3A weak inducer", footnotes: [] },
  { drug: "atomoxetine", target: "CYP2D6", kind: "substrate", fdaClass: "sensitive", cell: "2D6 sensitive substrate", footnotes: [] },
  { drug: "atorvastatin", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderate substrate", footnotes: [] },
  { drug: "avanafil", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "belumosudil", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp; BCRP inhibitor", footnotes: [] },
  { drug: "bosentan", target: "CYP3A4", kind: "inducer", fdaClass: "moderate", cell: "3A moderate inducer", footnotes: [] },
  { drug: "Brigatinib", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderately sensitive substrate", footnotes: [] },
  { drug: "budesonide", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "bupropion", target: "CYP2D6", kind: "inhibitor", fdaClass: "strong", cell: "2D6 strong inhibitor", footnotes: [2] },
  { drug: "bupropion", target: "CYP2B6", kind: "substrate", fdaClass: "sensitive", cell: "2B6 sensitive substrate", footnotes: [2] },
  { drug: "buspirone", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "caffeine", target: "CYP1A2", kind: "substrate", fdaClass: "sensitive", cell: "1A2 sensitive substrate", footnotes: [] },
  { drug: "capmatinib", target: "CYP1A2", kind: "inhibitor", fdaClass: "moderate", cell: "1A2 moderate inhibitor", footnotes: [] },
  { drug: "capmatinib", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp; BCRP inhibitor", footnotes: [] },
  { drug: "carbamazepine", target: "CYP2B6", kind: "inducer", fdaClass: "strong", cell: "2B6; 3A strong inducer", footnotes: [] },
  { drug: "carbamazepine", target: "CYP3A4", kind: "inducer", fdaClass: "strong", cell: "2B6; 3A strong inducer", footnotes: [] },
  { drug: "carbamazepine", target: "CYP2C9", kind: "inducer", fdaClass: "weak", cell: "2C9 weak inducer", footnotes: [] },
  { drug: "celecoxib", target: "CYP2D6", kind: "inhibitor", fdaClass: "weak", cell: "2D6 weak inhibitor", footnotes: [3] },
  { drug: "celecoxib", target: "CYP2C9", kind: "substrate", fdaClass: "sensitive", cell: "2C9 sensitive substrate", footnotes: [3] },
  { drug: "cenobamate", target: "CYP2C19", kind: "inhibitor", fdaClass: "moderate", cell: "2C19 moderate inhibitor", footnotes: [4] },
  { drug: "cenobamate", target: "CYP3A4", kind: "inducer", fdaClass: "moderate", cell: "CYP3A moderate inducer b", footnotes: [4] },
  { drug: "ceritinib", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "ceritinib", target: "CYP2C9", kind: "inhibitor", fdaClass: "weak", cell: "2C9 weak inhibitor", footnotes: [] },
  { drug: "chlorzoxazone", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A weak inhibitor", footnotes: [] },
  { drug: "cilostazol", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A weak inhibitor", footnotes: [] },
  { drug: "cimetidine", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A; 1A2; 2D6 weak inhibitor", footnotes: [] },
  { drug: "cimetidine", target: "CYP1A2", kind: "inhibitor", fdaClass: "weak", cell: "3A; 1A2; 2D6 weak inhibitor", footnotes: [] },
  { drug: "cimetidine", target: "CYP2D6", kind: "inhibitor", fdaClass: "weak", cell: "3A; 1A2; 2D6 weak inhibitor", footnotes: [] },
  { drug: "cinacalcet", target: "CYP2D6", kind: "inhibitor", fdaClass: "moderate", cell: "2D6 moderate inhibitor", footnotes: [] },
  { drug: "ciprofloxacin", target: "CYP1A2", kind: "inhibitor", fdaClass: "moderate", cell: "1A2 ^20; 3A moderate inhibitor", footnotes: [20] },
  { drug: "ciprofloxacin", target: "CYP3A4", kind: "inhibitor", fdaClass: "moderate", cell: "1A2 ^20; 3A moderate inhibitor", footnotes: [20] },
  { drug: "clarithromycin", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "clarithromycin", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp; OATP1B1; OATP1B3 inhibitor", footnotes: [] },
  { drug: "clobazam", target: "CYP2D6", kind: "inhibitor", fdaClass: "weak", cell: "2D6 weak inhibitor", footnotes: [] },
  { drug: "clopidogrel", target: "CYP2C8", kind: "inhibitor", fdaClass: "moderate", cell: "2C8 moderate inhibitor", footnotes: [] },
  { drug: "clopidogrel", target: "CYP2B6", kind: "inhibitor", fdaClass: "weak", cell: "2B6 weak inhibitor", footnotes: [] },
  { drug: "clotrimazole", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A weak inhibitor", footnotes: [] },
  { drug: "clozapine", target: "CYP1A2", kind: "substrate", fdaClass: "moderate-sensitive", cell: "1A2 moderate sensitive substrate", footnotes: [] },
  { drug: "cobicistat", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "cobicistat", target: "CYP2D6", kind: "inhibitor", fdaClass: "weak", cell: "2D6 weak inhibitor", footnotes: [] },
  { drug: "cobicistat", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp inhibitor", footnotes: [] },
  { drug: "colchicine", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderate sensitive substrate", footnotes: [] },
  { drug: "conivaptan", target: "CYP3A4", kind: "inhibitor", fdaClass: "moderate", cell: "3A moderate inhibitor ^5", footnotes: [5] },
  { drug: "conivaptan", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "crizotinib", target: "CYP3A4", kind: "inhibitor", fdaClass: "moderate", cell: "3A moderate inhibitor", footnotes: [] },
  { drug: "cyclosporine", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A weak inhibitor", footnotes: [] },
  { drug: "cyclosporine", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp; BCRP; OATP1B1; OATP1B3 inhibitor", footnotes: [] },
  { drug: "dabigatran etexilate", target: "P-gp", kind: "substrate", fdaClass: null, cell: "P-gp substrate", footnotes: [] },
  { drug: "dabrafenib", target: "CYP3A4", kind: "inducer", fdaClass: "moderate", cell: "3A moderate inducer", footnotes: [] },
  { drug: "dabrafenib", target: "CYP2C9", kind: "inducer", fdaClass: "weak", cell: "2C9 weak inducer", footnotes: [] },
  { drug: "danicopan", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp; BCRP inhibitor", footnotes: [] },
  { drug: "darifenacin", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "darunavir", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [6] },
  { drug: "dasatinib", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "deferasirox", target: "CYP2C8", kind: "inhibitor", fdaClass: "moderate", cell: "2C8 moderate inhibitor", footnotes: [] },
  { drug: "desipramine", target: "CYP2D6", kind: "substrate", fdaClass: "sensitive", cell: "2D6 sensitive substrate", footnotes: [] },
  { drug: "desloratadine", target: "CYP2C8", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2C8 moderately sensitive substrate", footnotes: [] },
  { drug: "dextromethorphan", target: "CYP2D6", kind: "substrate", fdaClass: "sensitive", cell: "2D6 sensitive substrate", footnotes: [] },
  { drug: "diazepam", target: "CYP2C19", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2C19 moderate sensitive substrate", footnotes: [] },
  { drug: "digoxin", target: "P-gp", kind: "substrate", fdaClass: null, cell: "P-gp substrate", footnotes: [] },
  { drug: "diltiazem", target: "CYP3A4", kind: "inhibitor", fdaClass: "moderate", cell: "3A moderate inhibitor", footnotes: [7] },
  { drug: "diosmin", target: "CYP2C9", kind: "inhibitor", fdaClass: "weak", cell: "2C9 weak inhibitor", footnotes: [] },
  { drug: "disulfiram", target: "CYP2C9", kind: "inhibitor", fdaClass: "weak", cell: "2C9 weak inhibitor", footnotes: [] },
  { drug: "dronedarone", target: "CYP3A4", kind: "inhibitor", fdaClass: "moderate", cell: "3A moderate inhibitor", footnotes: [] },
  { drug: "dronedarone", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "dronedarone", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp inhibitor", footnotes: [] },
  { drug: "duloxetine", target: "CYP2D6", kind: "inhibitor", fdaClass: "moderate", cell: "2D6 moderate inhibitor", footnotes: [] },
  { drug: "duloxetine", target: "CYP1A2", kind: "substrate", fdaClass: "sensitive", cell: "1A2 sensitive substrate", footnotes: [] },
  { drug: "edoxaban", target: "P-gp", kind: "substrate", fdaClass: null, cell: "P-gp substrate", footnotes: [] },
  { drug: "efavirenz", target: "CYP3A4", kind: "inducer", fdaClass: "moderate", cell: "3A; 2B6; 2C19 moderate inducer", footnotes: [] },
  { drug: "efavirenz", target: "CYP2B6", kind: "inducer", fdaClass: "moderate", cell: "3A; 2B6; 2C19 moderate inducer", footnotes: [] },
  { drug: "efavirenz", target: "CYP2C19", kind: "inducer", fdaClass: "moderate", cell: "3A; 2B6; 2C19 moderate inducer", footnotes: [] },
  { drug: "efavirenz", target: "CYP2B6", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2B6 moderate sensitive substrate", footnotes: [] },
  { drug: "elagolix", target: "CYP3A4", kind: "inducer", fdaClass: "weak", cell: "3A weak inducer", footnotes: [] },
  { drug: "eletriptan", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "eliglustat", target: "CYP2D6", kind: "substrate", fdaClass: "sensitive", cell: "2D6 sensitive substrate", footnotes: [] },
  { drug: "eliglustat", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderate sensitive substrate", footnotes: [] },
  { drug: "elvitegravir and ritonavir", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "Entrectinib", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A weak inhibitor", footnotes: [] },
  { drug: "Entrectinib", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "enzalutamide", target: "CYP3A4", kind: "inducer", fdaClass: "strong", cell: "3A strong inducer", footnotes: [] },
  { drug: "enzalutamide", target: "CYP2C9", kind: "inducer", fdaClass: "moderate", cell: "2C9; 2C19 moderate inducer", footnotes: [] },
  { drug: "enzalutamide", target: "CYP2C19", kind: "inducer", fdaClass: "moderate", cell: "2C9; 2C19 moderate inducer", footnotes: [] },
  { drug: "eplerenone", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "erythromycin", target: "CYP3A4", kind: "inhibitor", fdaClass: "moderate", cell: "3A moderate inhibitor", footnotes: [] },
  { drug: "erythromycin", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp inhibitor", footnotes: [] },
  { drug: "escitalopram", target: "CYP2D6", kind: "inhibitor", fdaClass: "weak", cell: "2D6 weak inhibitor", footnotes: [] },
  { drug: "etravirine", target: "CYP3A4", kind: "inducer", fdaClass: "moderate", cell: "3A moderate inducer", footnotes: [] },
  { drug: "everolimus", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "felbamate", target: "CYP2C19", kind: "inhibitor", fdaClass: "moderate", cell: "2C19 moderate inhibitor", footnotes: [] },
  { drug: "felodipine", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "fexofenadine", target: "P-gp", kind: "substrate", fdaClass: null, cell: "OATP1B1; OATP1B3; P-gp substrate", footnotes: [] },
  { drug: "fezolinetant", target: "CYP1A2", kind: "substrate", fdaClass: "sensitive", cell: "1A2 sensitive substrate", footnotes: [] },
  { drug: "fluconazole", target: "CYP2C19", kind: "inhibitor", fdaClass: "strong", cell: "2C19 strong inhibitor", footnotes: [] },
  { drug: "fluconazole", target: "CYP3A4", kind: "inhibitor", fdaClass: "moderate", cell: "3A; 2C9 moderate inhibitor", footnotes: [] },
  { drug: "fluconazole", target: "CYP2C9", kind: "inhibitor", fdaClass: "moderate", cell: "3A; 2C9 moderate inhibitor", footnotes: [] },
  { drug: "fluoxetine", target: "CYP2C19", kind: "inhibitor", fdaClass: "strong", cell: "2C19; 2D6 strong inhibitor", footnotes: [] },
  { drug: "fluoxetine", target: "CYP2D6", kind: "inhibitor", fdaClass: "strong", cell: "2C19; 2D6 strong inhibitor", footnotes: [] },
  { drug: "fluvastatin", target: "CYP2C9", kind: "inhibitor", fdaClass: "weak", cell: "2C9 weak inhibitor", footnotes: [] },
  { drug: "fluvoxamine", target: "CYP1A2", kind: "inhibitor", fdaClass: "strong", cell: "1A2; 2C19 strong inhibitor", footnotes: [8] },
  { drug: "fluvoxamine", target: "CYP2C19", kind: "inhibitor", fdaClass: "strong", cell: "1A2; 2C19 strong inhibitor", footnotes: [8] },
  { drug: "fluvoxamine", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A; 2C9; 2D6 weak inhibitor", footnotes: [8] },
  { drug: "fluvoxamine", target: "CYP2C9", kind: "inhibitor", fdaClass: "weak", cell: "3A; 2C9; 2D6 weak inhibitor", footnotes: [8] },
  { drug: "fluvoxamine", target: "CYP2D6", kind: "inhibitor", fdaClass: "weak", cell: "3A; 2C9; 2D6 weak inhibitor", footnotes: [8] },
  { drug: "fosaprepitant", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A weak inhibitor", footnotes: [] },
  { drug: "fostamatinib", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderately sensitive substrate", footnotes: [] },
  { drug: "fostamatinib", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp; BCRP inhibitor", footnotes: [] },
  { drug: "gemfibrozil", target: "CYP2C8", kind: "inhibitor", fdaClass: "strong", cell: "2C8 strong inhibitor", footnotes: [] },
  { drug: "glimepiride", target: "CYP2C9", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2C9 moderate sensitive substrate", footnotes: [] },
  { drug: "grapefruit juice", target: "CYP3A4", kind: "inhibitor", fdaClass: "moderate", cell: "3A moderate inhibitor", footnotes: [9] },
  { drug: "ibrutinib", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "idelalisib", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "imatinib", target: "CYP3A4", kind: "inhibitor", fdaClass: "moderate", cell: "3A moderate inhibitor", footnotes: [] },
  { drug: "imipramine", target: "CYP2D6", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2D6 moderate sensitive substrate", footnotes: [] },
  { drug: "indinavir", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [6] },
  { drug: "indinavir and ritonavir", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "isavuconazole", target: "CYP3A4", kind: "inhibitor", fdaClass: "moderate", cell: "3A moderate inhibitor", footnotes: [] },
  { drug: "isavuconazole", target: "CYP2B6", kind: "inducer", fdaClass: "weak", cell: "2B6 weak inducer", footnotes: [] },
  { drug: "isavuconazole", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "istradefylline", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A weak inhibitor", footnotes: [] },
  { drug: "itraconazole", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "itraconazole", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp inhibitor", footnotes: [] },
  { drug: "ivabradine", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "ivacaftor", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A weak inhibitor", footnotes: [] },
  { drug: "ivosidenib", target: "CYP3A4", kind: "inducer", fdaClass: "strong", cell: "3A strong inducer", footnotes: [10] },
  { drug: "ketoconazole", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "ketoconazole", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp inhibitor", footnotes: [] },
  { drug: "labetalol", target: "CYP2D6", kind: "inhibitor", fdaClass: "weak", cell: "2D6 weak inhibitor", footnotes: [] },
  { drug: "lansoprazole", target: "CYP2C19", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2C19 moderate sensitive substrate", footnotes: [11] },
  { drug: "lapatinib", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp inhibitor", footnotes: [] },
  { drug: "Larotrectinib", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A weak inhibitor", footnotes: [] },
  { drug: "Larotrectinib", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderately sensitive substrate", footnotes: [] },
  { drug: "Lazertinib", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A weak inhibitor", footnotes: [] },
  { drug: "lemborexant", target: "CYP2B6", kind: "inducer", fdaClass: "weak", cell: "2B6 weak inducer", footnotes: [] },
  { drug: "lemborexant", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "leniolisib", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderately sensitive substrate", footnotes: [] },
  { drug: "lomitapide", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A weak inhibitor", footnotes: [] },
  { drug: "lomitapide", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "Loperamide", target: "CYP2C8", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2C8 and 3A moderately sensitive substrate", footnotes: [] },
  { drug: "Loperamide", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2C8 and 3A moderately sensitive substrate", footnotes: [] },
  { drug: "Loperamide", target: "P-gp", kind: "substrate", fdaClass: null, cell: "P-gp transporter substrate", footnotes: [] },
  { drug: "lopinavir and ritonavir", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "lopinavir and ritonavir", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp; OATP1B1; OATP1B3 inhibitor", footnotes: [] },
  { drug: "lorcaserin", target: "CYP2D6", kind: "inhibitor", fdaClass: "moderate", cell: "2D6 moderate inhibitor", footnotes: [] },
  { drug: "lorlatinib", target: "CYP3A4", kind: "inducer", fdaClass: "moderate", cell: "3A moderate inducer", footnotes: [] },
  { drug: "lorlatinib", target: "CYP2B6", kind: "inducer", fdaClass: "weak", cell: "2B6; 2C9 weak inducer", footnotes: [] },
  { drug: "lorlatinib", target: "CYP2C9", kind: "inducer", fdaClass: "weak", cell: "2B6; 2C9 weak inducer", footnotes: [] },
  { drug: "lovastatin", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "lumacaftor and ivacaftor", target: "CYP3A4", kind: "inducer", fdaClass: "strong", cell: "3A strong inducer", footnotes: [] },
  { drug: "lurasidone", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "maraviroc", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "melatonin", target: "CYP1A2", kind: "substrate", fdaClass: "sensitive", cell: "1A2 sensitive substrate", footnotes: [] },
  { drug: "methoxsalen", target: "CYP1A2", kind: "inhibitor", fdaClass: "moderate", cell: "1A2 moderate inhibitor", footnotes: [] },
  { drug: "metoprolol", target: "CYP2D6", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2D6 moderate sensitive substrate", footnotes: [] },
  { drug: "mexiletine", target: "CYP1A2", kind: "inhibitor", fdaClass: "moderate", cell: "1A2 moderate inhibitor", footnotes: [] },
  { drug: "miconazole", target: "CYP2C9", kind: "inhibitor", fdaClass: "moderate", cell: "2C9 moderate inhibitor", footnotes: [] },
  { drug: "midazolam", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "mirabegron", target: "CYP2D6", kind: "inhibitor", fdaClass: "moderate", cell: "2D6 moderate inhibitor", footnotes: [] },
  { drug: "mitotane", target: "CYP3A4", kind: "inducer", fdaClass: "strong", cell: "3A strong inducer", footnotes: [] },
  { drug: "mobocertinib", target: "CYP3A4", kind: "inducer", fdaClass: "weak", cell: "3A weak inducer", footnotes: [] },
  { drug: "mobocertinib", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "modafinil", target: "CYP3A4", kind: "inducer", fdaClass: "weak", cell: "3A weak inducer", footnotes: [12] },
  { drug: "montelukast", target: "CYP2C8", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2C8 moderate sensitive substrate", footnotes: [] },
  { drug: "naloxegol", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "nebivolol", target: "CYP2D6", kind: "substrate", fdaClass: "sensitive", cell: "2D6 sensitive substrate", footnotes: [] },
  { drug: "nefazodone", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "nelfinavir", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "nevirapine", target: "CYP2B6", kind: "inducer", fdaClass: "weak", cell: "2B6 weak inducer", footnotes: [] },
  { drug: "nisoldipine", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "nortriptyline", target: "CYP2D6", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2D6 moderate sensitive substrate", footnotes: [] },
  { drug: "omeprazole", target: "CYP2C19", kind: "inhibitor", fdaClass: "weak", cell: "2C19 weak inhibitor", footnotes: [] },
  { drug: "omeprazole", target: "CYP2C19", kind: "substrate", fdaClass: "sensitive", cell: "2C19 sensitive substrate", footnotes: [] },
  { drug: "oral contraceptives", target: "CYP1A2", kind: "inhibitor", fdaClass: "moderate", cell: "1A2 moderate inhibitor", footnotes: [] },
  { drug: "paritaprevir and ritonavir and (ombitasvir and/or dasabuvir)", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "paroxetine", target: "CYP2D6", kind: "inhibitor", fdaClass: "strong", cell: "2D6 strong inhibitor", footnotes: [] },
  { drug: "peginterferon alpha-2a", target: "CYP1A2", kind: "inhibitor", fdaClass: "weak", cell: "1A2 weak inhibitor", footnotes: [] },
  { drug: "perphenazine", target: "CYP2D6", kind: "substrate", fdaClass: "sensitive", cell: "2D6 sensitive substrate", footnotes: [] },
  { drug: "pexidartinib", target: "CYP3A4", kind: "inducer", fdaClass: "moderate", cell: "3A moderate inducer", footnotes: [] },
  { drug: "phenobarbital", target: "CYP3A4", kind: "inducer", fdaClass: "moderate", cell: "3A moderate inducer", footnotes: [] },
  { drug: "phenytoin", target: "CYP3A4", kind: "inducer", fdaClass: "strong", cell: "3A strong inducer", footnotes: [] },
  { drug: "phenytoin", target: "CYP1A2", kind: "inducer", fdaClass: "moderate", cell: "1A2; 2C19 moderate inducer", footnotes: [] },
  { drug: "phenytoin", target: "CYP2C19", kind: "inducer", fdaClass: "moderate", cell: "1A2; 2C19 moderate inducer", footnotes: [] },
  { drug: "phenytoin", target: "CYP2C9", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2C9 moderate sensitive substrate", footnotes: [] },
  { drug: "pimozide", target: "CYP2D6", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2D6 and 3A moderately sensitive substrate", footnotes: [] },
  { drug: "pimozide", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2D6 and 3A moderately sensitive substrate", footnotes: [] },
  { drug: "pioglitazone", target: "CYP2C8", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2C8 moderate sensitive substrate", footnotes: [] },
  { drug: "piperine", target: "CYP2C9", kind: "inhibitor", fdaClass: "moderate", cell: "2C9 moderate inhibitor", footnotes: [] },
  { drug: "piperine", target: "CYP1A2", kind: "inhibitor", fdaClass: "weak", cell: "1A2 weak inhibitor", footnotes: [] },
  { drug: "pirfenidone", target: "CYP1A2", kind: "substrate", fdaClass: "moderate-sensitive", cell: "1A2 moderate sensitive substrate", footnotes: [] },
  { drug: "Pirtobrutinib", target: "CYP2C8", kind: "inhibitor", fdaClass: "moderate", cell: "2C8 moderate inhibitor", footnotes: [] },
  { drug: "Pirtobrutinib", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A and 2C19 weak inhibitor", footnotes: [] },
  { drug: "Pirtobrutinib", target: "CYP2C19", kind: "inhibitor", fdaClass: "weak", cell: "3A and 2C19 weak inhibitor", footnotes: [] },
  { drug: "Pirtobrutinib", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "BCRP and P-gp transporters inhibitor", footnotes: [] },
  { drug: "posaconazole", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "Pralsetinib", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderately sensitive substrate", footnotes: [] },
  { drug: "primidone", target: "CYP3A4", kind: "inducer", fdaClass: "moderate", cell: "3A moderate inducer", footnotes: [] },
  { drug: "propafenone", target: "CYP2D6", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2D6 moderate sensitive substrate", footnotes: [] },
  { drug: "propafenone", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp inhibitor", footnotes: [] },
  { drug: "propranolol", target: "CYP2D6", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2D6 moderate sensitive substrate", footnotes: [] },
  { drug: "quetiapine", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "quinidine", target: "CYP2D6", kind: "inhibitor", fdaClass: "strong", cell: "2D6 strong inhibitor", footnotes: [] },
  { drug: "quinidine", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp inhibitor", footnotes: [] },
  { drug: "R-venlafaxine", target: "CYP2D6", kind: "substrate", fdaClass: "sensitive", cell: "2D6 sensitive substrate", footnotes: [] },
  { drug: "rabeprazole", target: "CYP2C19", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2C19 moderate sensitive substrate", footnotes: [] },
  { drug: "ramelteon", target: "CYP1A2", kind: "substrate", fdaClass: "sensitive", cell: "1A2 sensitive substrate", footnotes: [] },
  { drug: "ranitidine", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A weak inhibitor", footnotes: [] },
  { drug: "ranolazine", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A weak inhibitor", footnotes: [] },
  { drug: "ranolazine", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp ; OCT2; MATE1; MATE2-K inhibitor", footnotes: [] },
  { drug: "repaglinide", target: "CYP2C8", kind: "substrate", fdaClass: "sensitive", cell: "2C8 sensitive substrate", footnotes: [] },
  { drug: "resmetirom", target: "CYP2C8", kind: "inhibitor", fdaClass: "weak", cell: "2C8 weak inhibitor", footnotes: [] },
  { drug: "resmetirom", target: "CYP2C8", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2C8 moderately sensitive substrate", footnotes: [] },
  { drug: "Repotrectinib", target: "CYP3A4", kind: "inducer", fdaClass: "moderate", cell: "3A moderate inducer", footnotes: [] },
  { drug: "Repotrectinib", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "rifampin", target: "CYP3A4", kind: "inducer", fdaClass: "strong", cell: "3A; 2C19 strong inducer", footnotes: [] },
  { drug: "rifampin", target: "CYP2C19", kind: "inducer", fdaClass: "strong", cell: "3A; 2C19 strong inducer", footnotes: [] },
  { drug: "rifampin", target: "CYP1A2", kind: "inducer", fdaClass: "moderate", cell: "1A2, 2B6; 2C8; 2C9 moderate inducer", footnotes: [] },
  { drug: "rifampin", target: "CYP2B6", kind: "inducer", fdaClass: "moderate", cell: "1A2, 2B6; 2C8; 2C9 moderate inducer", footnotes: [] },
  { drug: "rifampin", target: "CYP2C8", kind: "inducer", fdaClass: "moderate", cell: "1A2, 2B6; 2C8; 2C9 moderate inducer", footnotes: [] },
  { drug: "rifampin", target: "CYP2C9", kind: "inducer", fdaClass: "moderate", cell: "1A2, 2B6; 2C8; 2C9 moderate inducer", footnotes: [] },
  { drug: "rilpivirine", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderate sensitive substrate", footnotes: [] },
  { drug: "ritonavir", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [14, 15, 16] },
  { drug: "ritonavir", target: "CYP2B6", kind: "inducer", fdaClass: "weak", cell: "2B6; 2C9; 2C19 weak inducer", footnotes: [14, 15, 16] },
  { drug: "ritonavir", target: "CYP2C9", kind: "inducer", fdaClass: "weak", cell: "2B6; 2C9; 2C19 weak inducer", footnotes: [14, 15, 16] },
  { drug: "ritonavir", target: "CYP2C19", kind: "inducer", fdaClass: "weak", cell: "2B6; 2C9; 2C19 weak inducer", footnotes: [14, 15, 16] },
  { drug: "rivaroxaban", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderate sensitive substrate", footnotes: [] },
  { drug: "rolapitant", target: "CYP2D6", kind: "inhibitor", fdaClass: "moderate", cell: "2D6 moderate inhibitor", footnotes: [17] },
  { drug: "rolapitant", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp; BCRP inhibitor", footnotes: [17] },
  { drug: "rosiglitazone", target: "CYP2C8", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2C8 moderate sensitive substrate", footnotes: [] },
  { drug: "rufinamide", target: "CYP3A4", kind: "inducer", fdaClass: "weak", cell: "3A weak inducer", footnotes: [] },
  { drug: "S-mephenytoin", target: "CYP2C19", kind: "substrate", fdaClass: "sensitive", cell: "2C19 sensitive substrate", footnotes: [] },
  { drug: "S-venlafaxine", target: "CYP2D6", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2D6 moderate sensitive substrate", footnotes: [] },
  { drug: "saquinavir", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [6] },
  { drug: "saquinavir and ritonavir", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "saquinavir and ritonavir", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp inhibitor", footnotes: [] },
  { drug: "selexipag", target: "CYP2C8", kind: "substrate", fdaClass: "sensitive", cell: "2C8 sensitive substrate", footnotes: [21] },
  { drug: "Selpercatinib", target: "CYP2C8", kind: "inhibitor", fdaClass: "moderate", cell: "2C8 moderate inhibitor", footnotes: [] },
  { drug: "Selpercatinib", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A weak inhibitor", footnotes: [] },
  { drug: "Selpercatinib", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderately sensitive substrate", footnotes: [] },
  { drug: "sertraline", target: "CYP2D6", kind: "inhibitor", fdaClass: "weak", cell: "2D6 weak inhibitor", footnotes: [] },
  { drug: "sevabertinib", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A weak inhibitor", footnotes: [] },
  { drug: "sevabertinib", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderately sensitive substrate", footnotes: [] },
  { drug: "sildenafil", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "simvastatin", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "sirolimus", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "Sofosbuvir and Velpatasvir and Voxilaprevir", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp; BCRP; OATP1B1; OATP1B3 inhibitor", footnotes: [] },
  { drug: "sotorasib", target: "CYP3A4", kind: "inducer", fdaClass: "moderate", cell: "3A moderate inducer", footnotes: [] },
  { drug: "St. John’s wort", target: "CYP3A4", kind: "inducer", fdaClass: "strong", cell: "3A strong inducer", footnotes: [18] },
  { drug: "tacrolimus", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "tadalafil", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderate sensitive substrate", footnotes: [] },
  { drug: "taletrectinib", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderately sensitive substrate", footnotes: [] },
  { drug: "tasimelteon", target: "CYP1A2", kind: "substrate", fdaClass: "sensitive", cell: "1A2 sensitive substrate", footnotes: [] },
  { drug: "Tazemetostat", target: "CYP2C8", kind: "inhibitor", fdaClass: "weak", cell: "2C8 weak inhibitor", footnotes: [] },
  { drug: "Tazemetostat", target: "CYP3A4", kind: "inducer", fdaClass: "weak", cell: "3A weak inducer", footnotes: [] },
  { drug: "Tazemetostat", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderately sensitive substrate", footnotes: [] },
  { drug: "telithromycin", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "tenofovir", target: "CYP2B6", kind: "inhibitor", fdaClass: "weak", cell: "2B6 weak inhibitor", footnotes: [1] },
  { drug: "terbinafine", target: "CYP2D6", kind: "inhibitor", fdaClass: "strong", cell: "2D6 strong inhibitor", footnotes: [] },
  { drug: "teriflunomide", target: "CYP2C8", kind: "inhibitor", fdaClass: "moderate", cell: "2C8 moderate inhibitor", footnotes: [] },
  { drug: "teriflunomide", target: "CYP1A2", kind: "inducer", fdaClass: "moderate", cell: "1A2 moderate inducer", footnotes: [] },
  { drug: "theophylline", target: "CYP1A2", kind: "substrate", fdaClass: "moderate-sensitive", cell: "1A2 moderate sensitive substrate", footnotes: [] },
  { drug: "ticagrelor", target: "CYP3A4", kind: "inhibitor", fdaClass: "weak", cell: "3A weak inhibitor", footnotes: [] },
  { drug: "ticagrelor", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "ticlopidine", target: "CYP2C19", kind: "inhibitor", fdaClass: "strong", cell: "2C19 strong inhibitor", footnotes: [] },
  { drug: "ticlopidine", target: "CYP2B6", kind: "inhibitor", fdaClass: "weak", cell: "2B6 weak inhibitor", footnotes: [] },
  { drug: "tipranavir", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [6] },
  { drug: "tipranavir and ritonavir", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "tizanidine", target: "CYP1A2", kind: "substrate", fdaClass: "sensitive", cell: "1A2 sensitive substrate", footnotes: [] },
  { drug: "tobacco (smoking)", target: "CYP1A2", kind: "inducer", fdaClass: "moderate", cell: "1A2 moderate inducer", footnotes: [] },
  { drug: "tolbutamide", target: "CYP2C9", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2C9 moderate sensitive substrate", footnotes: [] },
  { drug: "tolterodine", target: "CYP2D6", kind: "substrate", fdaClass: "sensitive", cell: "2D6 sensitive substrate", footnotes: [] },
  { drug: "tolvaptan", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "tramadol", target: "CYP2D6", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2D6 moderate sensitive substrate", footnotes: [] },
  { drug: "triazolam", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "trimethoprim", target: "CYP2C8", kind: "inhibitor", fdaClass: "weak", cell: "2C8 weak inhibitor", footnotes: [] },
  { drug: "trimipramine", target: "CYP2D6", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2D6 moderate sensitive substrate", footnotes: [] },
  { drug: "tucatinib", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "tucatinib", target: "CYP2C8", kind: "inhibitor", fdaClass: "weak", cell: "2C8 weak inhibitor", footnotes: [] },
  { drug: "tucatinib", target: "CYP2C8", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2C8 moderately sensitive substrate", footnotes: [] },
  { drug: "tucatinib", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp transporter inhibitor", footnotes: [] },
  { drug: "vardenafil", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "vemurafenib", target: "CYP1A2", kind: "inhibitor", fdaClass: "moderate", cell: "1A2 moderate inhibitor", footnotes: [] },
  { drug: "vemurafenib", target: "CYP2D6", kind: "inhibitor", fdaClass: "weak", cell: "2D6 weak inhibitor", footnotes: [] },
  { drug: "vemurafenib", target: "CYP3A4", kind: "inducer", fdaClass: "weak", cell: "3A weak inducer", footnotes: [] },
  { drug: "venetoclax", target: "CYP3A4", kind: "substrate", fdaClass: "sensitive", cell: "3A sensitive substrate", footnotes: [] },
  { drug: "verapamil", target: "CYP3A4", kind: "inhibitor", fdaClass: "moderate", cell: "3A moderate inhibitor", footnotes: [] },
  { drug: "verapamil", target: "P-gp", kind: "inhibitor", fdaClass: null, cell: "P-gp inhibitor", footnotes: [] },
  { drug: "voriconazole", target: "CYP3A4", kind: "inhibitor", fdaClass: "strong", cell: "3A strong inhibitor", footnotes: [] },
  { drug: "voriconazole", target: "CYP2C19", kind: "inhibitor", fdaClass: "moderate", cell: "2C19 moderate inhibitor", footnotes: [] },
  { drug: "voriconazole", target: "CYP2B6", kind: "inhibitor", fdaClass: "weak", cell: "2B6; 2C9; weak inhibitor", footnotes: [] },
  { drug: "voriconazole", target: "CYP2C9", kind: "inhibitor", fdaClass: "weak", cell: "2B6; 2C9; weak inhibitor", footnotes: [] },
  { drug: "voriconazole", target: "CYP2C19", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2C19 moderate sensitive substrate", footnotes: [] },
  { drug: "warfarin", target: "CYP2C9", kind: "substrate", fdaClass: "moderate-sensitive", cell: "2C9 moderate sensitive substrate", footnotes: [19] },
  { drug: "zanubrutinib", target: "CYP3A4", kind: "inducer", fdaClass: "weak", cell: "3A and 2C19 weak inducer", footnotes: [] },
  { drug: "zanubrutinib", target: "CYP2C19", kind: "inducer", fdaClass: "weak", cell: "3A and 2C19 weak inducer", footnotes: [] },
  { drug: "zanubrutinib", target: "CYP3A4", kind: "substrate", fdaClass: "moderate-sensitive", cell: "3A moderately sensitive substrate", footnotes: [] },
  { drug: "zileuton", target: "CYP1A2", kind: "inhibitor", fdaClass: "weak", cell: "1A2 weak inhibitor", footnotes: [] },
];
