/**
 * Print the FDA DDI agreement report and write docs/validation/fda-ddi-agreement.md.
 *
 *   npx --yes tsx scripts/fda-agreement.ts            # print + write
 *   npx --yes tsx scripts/fda-agreement.ts --check    # exit 1 if the md is stale
 *
 * Output is deterministic (no run timestamp) so regenerating does not churn.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { DRUGS } from "../src/lib/drugs/catalog.ts";
import { FDA_DDI_SOURCE, FDA_DDI_TABLE, FDA_DDI_FOOTNOTES } from "../src/lib/drugs/reference/fda-ddi-table.ts";
import { validateAgainstFda, type AgreementStats, type Discrepancy } from "../src/lib/drugs/reference/validate-fda.ts";
import {
  FDA_STRONG_PERPETRATOR_BASELINE_PCT,
  REVIEWED_DIRECTION_MISMATCHES,
} from "../src/lib/drugs/reference/fda-baseline.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outPath = resolve(root, "docs/validation/fda-ddi-agreement.md");

const r = validateAgainstFda(DRUGS);
const pct = (s: AgreementStats) => `${s.exactPct}% (${s.exact}/${s.compared})`;
const rpct = (s: AgreementStats) => `${s.rolePct}% (${s.roleAgree}/${s.compared})`;
const esc = (s: string | null | undefined) => (s ?? "—").replace(/\|/g, "\\|");

const TARGET_ORDER = ["CYP1A2", "CYP2B6", "CYP2C8", "CYP2C9", "CYP2C19", "CYP2D6", "CYP3A4", "P-gp"] as const;
const footnoteFor = (d: Discrepancy) => {
  const fns = new Set<number>();
  for (const e of FDA_DDI_TABLE) if (e.drug === d.fdaDrug && e.target === d.target) e.footnotes.forEach((f) => fns.add(f));
  return [...fns].sort((a, b) => a - b).map((f) => `fn ${f}`).join(", ");
};

const L: string[] = [];
L.push("# FDA DDI reference agreement (generated)");
L.push("");
L.push("> Generated by `npx --yes tsx scripts/fda-agreement.ts`. Do not hand-edit; re-run the script.");
L.push("> Educational teaching tool. **Not FDA-cleared**, not a medical device, not for clinical decisions.");
L.push("");
L.push("## Source");
L.push("");
L.push(`- ${FDA_DDI_SOURCE.title}: <${FDA_DDI_SOURCE.url}> (content current as of ${FDA_DDI_SOURCE.contentCurrentAsOf})`);
L.push(`- Companion page (index drugs only; checked, not transcribed): <${FDA_DDI_SOURCE.companionUrl}> (content current as of ${FDA_DDI_SOURCE.companionContentCurrentAsOf})`);
L.push(`- Retrieved ${FDA_DDI_SOURCE.retrieved}. Transcription: \`src/lib/drugs/reference/fda-ddi-table.ts\` (${FDA_DDI_TABLE.length} in-scope rows).`);
L.push("");
L.push("## Headline");
L.push("");
L.push("**Denominator:** only (drug, target, role) pairs that FDA's Table 1 actually lists **and** whose drug resolves to a catalog entry. Catalog drugs absent from the FDA table are never counted as disagreements.");
L.push("");
L.push(`- Pairs compared: **${r.overall.compared}** (from ${r.matched.length} FDA drug names matched to the catalog; ${r.drugsNotInCatalog.length} FDA names not in catalog)`);
L.push(`- Exact agreement (role + FDA class/grade): **${pct(r.overall)}**`);
L.push(`- Role agreement (same role on the target, class/grade ignored): **${rpct(r.overall)}**`);
L.push(`- FDA strong-inhibitor + strong-inducer pairs, exact: **${pct(r.strongPerpetrators)}**; role: ${rpct(r.strongPerpetrators)} (regression gate baseline: ${FDA_STRONG_PERPETRATOR_BASELINE_PCT}%)`);
L.push("");
L.push("| Category | Count | In formulary review list? |");
L.push("| --- | ---: | --- |");
L.push(`| direction_mismatch | ${r.counts.direction_mismatch} | yes |`);
L.push(`| strength_mismatch | ${r.counts.strength_mismatch} | yes |`);
L.push(`| missing_in_catalog | ${r.counts.missing_in_catalog} | yes |`);
L.push(`| not_in_fda | ${r.counts.not_in_fda} | no (informational) |`);
L.push(`| drug_not_in_catalog | ${r.counts.drug_not_in_catalog} | no (coverage) |`);
L.push("");
L.push(`Reviewed direction-mismatch allowlist entries: ${REVIEWED_DIRECTION_MISMATCHES.length}.`);
L.push("");
L.push("## Per target");
L.push("");
L.push("| Target | Pairs | Exact | Role | Strength mismatch | Direction mismatch | Missing |");
L.push("| --- | ---: | ---: | ---: | ---: | ---: | ---: |");
for (const t of TARGET_ORDER) {
  const s = r.perTarget[t];
  if (!s) continue;
  L.push(`| ${t === "CYP3A4" ? "CYP3A4 (FDA \"3A\")" : t} | ${s.compared} | ${s.exactPct}% | ${s.rolePct}% | ${s.strengthMismatch} | ${s.directionMismatch} | ${s.missing} |`);
}
L.push("");
L.push("## Formulary owner review list");
L.push("");
L.push("For the formulary owner (Grok Bot 5). Only direction_mismatch, strength_mismatch, and missing_in_catalog. No catalog rows were changed by this PR.");
L.push("Substrate grade mapping: FDA *sensitive* ↔ catalog `sensitive`; FDA *moderate sensitive* ↔ catalog `major`.");
L.push("");
L.push("| # | Category | FDA drug | Catalog id | Target | FDA says | Catalog says | FDA footnotes |");
L.push("| ---: | --- | --- | --- | --- | --- | --- | --- |");
r.reviewList.forEach((d, i) =>
  L.push(`| ${i + 1} | ${d.category} | ${esc(d.fdaDrug)} | \`${d.catalogId}\` | ${d.target} | ${esc(d.fdaRole)} | ${esc(d.catalogRole)} | ${footnoteFor(d) || "—"} |`),
);
L.push("");
const usedFns = new Set<number>();
for (const d of r.reviewList) footnoteFor(d).split(", ").filter(Boolean).forEach((f) => usedFns.add(Number(f.replace("fn ", ""))));
if (usedFns.size) {
  L.push("<details><summary>FDA footnotes cited above</summary>");
  L.push("");
  for (const f of [...usedFns].sort((a, b) => a - b)) L.push(`- **${f}.** ${FDA_DDI_FOOTNOTES[f]}`);
  L.push("");
  L.push("</details>");
  L.push("");
}
L.push("## Informational: not_in_fda (not disagreements)");
L.push("");
L.push("The catalog asserts an inhibitor/inducer role for an FDA-listed drug on a target where FDA's table lists none. FDA's table is illustrative, so these are not errors and are not in the review list.");
L.push("");
L.push(`<details><summary>${r.notInFda.length} catalog assertions</summary>`);
L.push("");
for (const d of r.notInFda) L.push(`- ${d.fdaDrug} (\`${d.catalogId}\`) · ${d.target} · ${d.catalogRole}`);
L.push("");
L.push("</details>");
L.push("");
L.push("## Coverage: FDA drugs not in catalog");
L.push("");
L.push(`<details><summary>${r.drugsNotInCatalog.length} names</summary>`);
L.push("");
L.push(r.drugsNotInCatalog.join(", "));
L.push("");
L.push("</details>");
L.push("");
L.push("## Method");
L.push("");
L.push("1. FDA Table 1 rows were parsed from the page HTML and split per target (e.g. `2D6; 3A weak inhibitor` → two rows). FDA \"3A\" maps to our `CYP3A4` key. Only targets the catalog models are kept (CYP1A2, 2B6, 2C8, 2C9, 2C19, 2D6, 3A, P-gp); FDA lists no CYP2E1 examples. P-gp rows carry no FDA class, so only role presence is compared.");
L.push("2. FDA names are resolved to catalog entries using the catalog's own `normalizeSearchText` + `stripSaltFormTokens`, tried against id → name → alias → brand, with `and` dropped so `lopinavir and ritonavir` ≈ `Lopinavir/ritonavir`. A short reviewed alias map covers `dabigatran etexilate`, `peginterferon alpha-2a`, `oral contraceptives` (→ `ethinyl-estradiol`). Enantiomers, active moieties (tenofovir), and single components of our combination products (trimethoprim) are deliberately not linked.");
L.push("3. Each FDA (drug, target, role) pair is classified: `match`; `strength_mismatch` (same role, different class/grade); `direction_mismatch` (FDA inhibitor vs our inducer only, or vice versa); `missing_in_catalog` (no role of that kind on that target).");
L.push("");
L.push("## Limitations");
L.push("");
L.push("- FDA's Table 1 is **illustrative, not exhaustive** (\"a guide and not considered a comprehensive list\"). Absence from FDA is not evidence that a role is wrong; hence `not_in_fda` is informational only.");
L.push("- FDA classes are defined by AUC change with index substrates; several depend on exposure conditions, preparation, or route (see FDA footnotes, e.g. grapefruit juice, ciprofloxacin/tizanidine, ritonavir). The catalog uses a coarser teaching scale; catalog `major` substrate is not a validated FDA class.");
L.push("- CYP3A4 vs CYP3A: FDA grades CYP3A as a whole; the catalog keys it as CYP3A4.");
L.push("- Only one catalog entry is compared per FDA name (the id/name match wins over release-form variants such as `-xr`).");
L.push("- Educational teaching tool. **Not FDA-cleared**; not a substitute for prescribing information or a pharmacist.");
L.push("");

const md = L.join("\n");
if (process.argv.includes("--check")) {
  const current = (() => {
    try {
      return readFileSync(outPath, "utf8");
    } catch {
      return "";
    }
  })();
  if (current !== md) {
    console.error("docs/validation/fda-ddi-agreement.md is stale; re-run scripts/fda-agreement.ts");
    process.exit(1);
  }
} else {
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, md);
}

console.log(`FDA DDI agreement (source current as of ${FDA_DDI_SOURCE.contentCurrentAsOf}, retrieved ${FDA_DDI_SOURCE.retrieved})`);
console.log(`Pairs compared (FDA-listed ∩ catalog): ${r.overall.compared}`);
console.log(`Exact agreement: ${pct(r.overall)}   Role agreement: ${rpct(r.overall)}`);
console.log(`FDA strong inhibitor/inducer exact: ${pct(r.strongPerpetrators)} (baseline ${FDA_STRONG_PERPETRATOR_BASELINE_PCT}%)`);
for (const t of TARGET_ORDER) {
  const s = r.perTarget[t];
  if (s) console.log(`  ${t.padEnd(8)} exact ${String(s.exactPct).padStart(5)}%  role ${String(s.rolePct).padStart(5)}%  n=${s.compared}`);
}
console.log("Counts:", r.counts);
console.log(`Review list: ${r.reviewList.length} items${process.argv.includes("--check") ? "" : ` → ${outPath}`}`);
