/**
 * Run the label gold set through the desk engine and write
 * docs/validation/label-gold-set.md.
 *
 *   npx --yes tsx scripts/gold-set-report.ts            # print summary + write
 *   npx --yes tsx scripts/gold-set-report.ts --check    # exit 1 if the md is stale
 *
 * Output is deterministic (no run timestamp) so regenerating does not churn.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { SEVERITY_LABEL } from "../src/lib/drugs/types.ts";
import {
  DROPPED_CANDIDATES,
  KNOWN_CONTRAINDICATION_GAPS,
  KNOWN_UNDERCALLS,
  LABEL_GOLD_SET,
  NOT_IN_CATALOG,
} from "../src/lib/drugs/reference/label-gold-set.ts";
import { evaluateGoldSet, type PairSeverity } from "../src/lib/drugs/reference/label-gold-set-eval.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outPath = resolve(root, "docs/validation/label-gold-set.md");

const results = evaluateGoldSet(LABEL_GOLD_SET);
const esc = (s: string) => s.replace(/\|/g, "\\|");
const sev = (s: PairSeverity) => `${s} (${SEVERITY_LABEL[s]})`;

const n = results.length;
const atFloor = results.filter((r) => r.meetsFloor).length;
const ciPairs = results.filter((r) => r.pair.expectContraindicated);
const exact = results.filter((r) => r.exactContraindicated).length;
const avoidPairs = results.filter((r) => r.pair.labelClass === "avoid");
const under = results.filter((r) => !r.meetsFloor);
const gaps = results.filter((r) => r.meetsFloor && r.pair.expectContraindicated && r.engine !== "contraindicated");

const L: string[] = [];
L.push("# Label-anchored gold set: end-to-end validation (generated)");
L.push("");
L.push("> Generated by `npx --yes tsx scripts/gold-set-report.ts`. Do not hand-edit; re-run the script.");
L.push("> Educational teaching desk, **not FDA-cleared**. No dosing guidance. Not a substitute for the label or a clinician.");
L.push("");
L.push("## Summary");
L.push("");
L.push(`| Measure | Count |`);
L.push(`|---|---|`);
L.push(`| Pairs (each tied to a verified FDA label statement) | ${n} |`);
L.push(`| Label says contraindicated | ${ciPairs.length} |`);
L.push(`| Label says avoid / not recommended | ${avoidPairs.length} |`);
L.push(`| Engine at or above floor (major, "Serious concern") | ${atFloor} / ${n} |`);
L.push(`| Exact match: label contraindicated and engine contraindicated ("Avoid together") | ${exact} / ${ciPairs.length} |`);
L.push(`| Contraindicated on label, engine major (meets floor, not exact) | ${gaps.length} |`);
L.push(`| Under-calls (engine below floor) | ${under.length} |`);
L.push("");
L.push("## Under-calls (for formulary owner, Grok Bot 5)");
L.push("");
if (!under.length) L.push("None.");
else {
  L.push("| Pair | Label says | Engine (pair-level) | Label | Quote |");
  L.push("|---|---|---|---|---|");
  for (const r of under)
    L.push(`| ${r.pair.drugA} + ${r.pair.drugB} | ${r.pair.labelClass} | ${sev(r.engine)} | ${esc(r.pair.labelDrug)}, ${esc(r.pair.labelSection)} | "${esc(r.pair.quote)}" |`);
}
L.push("");
L.push(`These are listed in \`KNOWN_UNDERCALLS\` (${KNOWN_UNDERCALLS.length}) so the suite stays green; a test fails when one starts passing so the list gets pruned. No catalog or engine data was changed.`);
L.push("");
L.push("## Contraindicated on the label, engine says major");
L.push("");
L.push("These meet the floor. Listed in `KNOWN_CONTRAINDICATION_GAPS` (" + KNOWN_CONTRAINDICATION_GAPS.length + ") for review; a test pins them either way.");
L.push("");
for (const r of gaps) L.push(`- ${r.pair.drugA} + ${r.pair.drugB}: engine ${sev(r.engine)}; ${esc(r.pair.labelDrug)} ${esc(r.pair.labelSection)}`);
L.push("");
L.push("## Every pair");
L.push("");
L.push("| # | Drug A | Drug B | Label | Section | Class | Engine (pair-level) | Result | Quote |");
L.push("|---|---|---|---|---|---|---|---|---|");
results.forEach((r, i) => {
  const p = r.pair;
  const result = !r.meetsFloor ? "UNDER-CALL" : r.exactContraindicated ? "pass (exact)" : "pass";
  const q = `"${esc(p.quote)}"${p.paraphrased ? " (paraphrased)" : ""}${p.labelExample ? ` · e.g. "${esc(p.labelExample)}"` : ""}`;
  L.push(`| ${i + 1} | ${p.drugA} | ${p.drugB} | [${esc(p.labelDrug)}](${p.url}) | ${esc(p.labelSection)} | ${p.labelClass} | ${sev(r.engine)} | ${result} | ${q} |`);
});
L.push("");
L.push("## Method");
L.push("");
L.push("1. Candidate pairs were drawn from the desk's teaching domains (psychiatry, MAOI/opioid, sleep, statins, antiarrhythmics/cardiology, antithrombotics, antimicrobials).");
L.push("2. Each statement was checked on the current DailyMed SPL for the named label (retrieved 2026-09-27). Quotes are verbatim substrings of that SPL text (\"…\" marks an elided span), no longer than 25 words, and carry no dose amounts.");
L.push("3. Inclusion: the label must say contraindicated, or explicitly avoid / not recommended / should not be used. Monitoring-only language does not qualify.");
L.push("4. Each pair's drugs are resolved to catalog ids with the desk's own search (`searchDrugs`), and a test asserts the typed query resolves to that id.");
L.push("5. The two-drug regimen is run through `analyze(ids, DEFAULT_HOST)` as the desk does (no doses entered). The pair's severity is the highest finding that involves **both** drugs; findings on one drug alone are excluded.");
L.push("6. Floor: both label classes require at least `major` (\"Serious concern\"). For contraindicated labels the stricter expectation is `contraindicated` (\"Avoid together\"), reported separately as exact matches.");
L.push("");
L.push("## Dropped candidates");
L.push("");
for (const d of DROPPED_CANDIDATES) L.push(`- **${esc(d.pair)}**: ${esc(d.reason)}`);
L.push("");
L.push("## Not in catalog");
L.push("");
for (const d of NOT_IN_CATALOG) L.push(`- **${d.drug}**: ${esc(d.reason)}`);
L.push("");
L.push("## Limitations");
L.push("");
L.push("- A curated set of well-documented examples, not an exhaustive interaction list; passing says nothing about pairs outside the set.");
L.push("- Default host only (adult, normal kidney/liver, default phenotypes). Conditional label statements (e.g. renal impairment) are not tested.");
L.push("- Several labels name a class (\"strong CYP3A4 inhibitors\", \"sedative hypnotics\") with examples; the pair uses a named example where the label gives one.");
L.push("- Labels change. Quotes reflect the SPL version retrieved on 2026-09-27; some links point to a repackager's SPL of the same labeling.");
L.push("- Educational tool, not FDA-cleared. It does not dose, and it does not decide care.");
L.push("");

const md = L.join("\n");
if (process.argv.includes("--check")) {
  const cur = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
  if (cur !== md) {
    console.error("docs/validation/label-gold-set.md is stale; run npx --yes tsx scripts/gold-set-report.ts");
    process.exit(1);
  }
  console.log("label-gold-set.md is up to date");
} else {
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, md);
  console.log(`pairs ${n} · at floor ${atFloor} · exact contraindicated ${exact}/${ciPairs.length} · gaps ${gaps.length} · under-calls ${under.length}`);
  for (const r of under) console.log(`  under: ${r.pair.id} engine=${r.engine} label=${r.pair.labelClass}`);
  console.log(`wrote ${outPath}`);
}
